function aa() {
  const flag = true;
  return flag && { name: "machao" };
}
const obj = aa();
console.log("obj===", obj);

var newList = [
  {
    author: { email: "xwgu007@gmail.com", name: "NateRobinson" },
    capabilities: { clusterMode: false },
    children: [],
    community: "",
    description: "一款基于 Blocklet Server 打造的去中心化薪资发放管理工具",
    did: "z8ia1Qx3edFD1ju6U7usk6wR8QBWoc6VUkmRQ",
    dist: {
      integrity:
        "sha512-qSyKgyEIOfEaz9r7ibfWnvonrCfkCQIWzb1i1+7bGMzNsBGx9+OmMuOsZVZIrd2MsNN6x77vJVDypXqkWnh61g==",
      tarball: "wage-assistant-0.1.1.tgz",
    },
    documentation: "",
    environments: [
      {
        default: "beta",
        description: "What's endpoint of the chain id?",
        name: "CHAIN_ID",
        required: true,
        secure: false,
      },
      {
        default: "https://beta.abtnetwork.io/api/",
        description: "What's endpoint of the chain?",
        name: "CHAIN_HOST",
        required: true,
        secure: false,
      },
      {
        default: "eth",
        description: "Blocklet wallet type must be set to eth",
        name: "BLOCKLET_WALLET_TYPE",
        required: true,
        secure: false,
      },
      {
        default: "",
        description: "evm chain id, mainnet is 1, rinkeby is 4...",
        name: "EVMCHAIN_ID",
        required: true,
        secure: false,
      },
      {
        default: "",
        description: "RPC url for web3 provider",
        name: "RPC_URL",
        required: true,
        secure: false,
      },
      {
        default: "",
        description: "ERC20 Token Address",
        name: "ERC20_TOKEN_ADDRESS",
        required: true,
        secure: false,
      },
      {
        default: "",
        description: "ERC20 Token Symbol",
        name: "ERC20_TOKEN_SYMBOL",
        required: true,
        secure: false,
      },
      {
        default: "",
        description: "ERC20 Token Decimal",
        name: "ERC20_TOKEN_DECIMAL",
        required: true,
        secure: false,
      },
    ],
    files: [
      "build",
      "logo.png",
      "README.md",
      "blocklet.md",
      "screenshots",
      "server/hooks/pre-start.js",
    ],
    gitHash: "268b95c67f4c0f7adab65b0896fad279e46a5ab9",
    group: "dapp",
    homepage: "",
    interfaces: [
      {
        name: "publicUrl",
        path: "/",
        port: "BLOCKLET_PORT",
        prefix: "*",
        protocol: "http",
        services: [
          {
            config: {
              blockUnauthenticated: true,
              ignoreUrls: ["/api/**"],
              invitedUserOnly: "not-first",
            },
            name: "@abtnode/auth-service",
          },
        ],
        type: "web",
      },
    ],
    keywords: ["blocklet", "react"],
    license: "",
    logo: "logo.png",
    main: "blocklet.zip",
    name: "wage-assistant",
    nftFactory: "z3CtLcXGB3eDzMgBby6LrEd3Lwcc2YMBsUoiC",
    path: "/dapp/wage-assistant",
    payment: {
      price: [
        {
          address: "z35nNRvYxBoHitx9yZ5ATS88psfShzPPBLxYD",
          value: 6.66,
          symbol: "ABT",
        },
      ],
      share: [
        {
          address: "z1gShFYDsiMfGtaerBTh2ydu75768xMYPQU",
          name: "developer",
          value: 0.7,
        },
        {
          address: "zNKXtdqz6Jbw5mKpojK2nP5gRNiEGJY3mNFF",
          name: "store",
          value: 0.3,
        },
      ],
    },
    repository: {
      type: "git",
      url: "git+https://github.com/NateRobinson/wage-assistant.git",
    },
    requirements: { abtnode: ">=1.4.0", cpu: "*", os: "*" },
    screenshots: [],
    scripts: {
      dev: "npm run start",
      preStart: "node server/hooks/pre-start.js",
    },
    signatures: [
      {
        type: "ED25519",
        name: "Blocklet Store",
        signer: "zNKXtdqz6Jbw5mKpojK2nP5gRNiEGJY3mNFF",
        pk: "z8VahoQa6oS63Ym3rfsmzZEt9Moonbg4JSUiit5J7DRAV",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-02-05T07:30:55.166Z",
        sig: "z2eUWJFu3KS5EKKaVEbwq53jGMJ2dMCTCY3e1SCZwSzWdTzGZXVaNuzywbiV4JjwtjCBL8Scddnjy76u3VhvEM3Cq",
      },
      {
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-02-05T07:30:49.899Z",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        name: "wage-assistant",
        pk: "z2UJYKL1BwBEn1mYCZGRbzRXzv28JAzoPBr7cUzkn8ih7",
        signer: "z1gShFYDsiMfGtaerBTh2ydu75768xMYPQU",
        type: "ED25519",
        sig: "z3u1qvcqBbyHZEhUdgujApWBFgUHTdrR4UudrLk41RYCEttcARZBMvtqK793NVuEGrT3vw2SaHaCeq6dwprSZGFV8",
      },
      {
        created: "2022-02-05T07:28:11.565Z",
        name: "wage-assistant",
        pk: "zDidzr4wuHHxGa5doLCQiWthGVgQfTUZDwyrqWoGcJyE",
        sig: "z3bFbkVW6TLnTWbWhcSwcfTZg5zWRXHqmNCBWV2yVDkstJSNGksJabj1D5Ei3n9xRF9dWmiQZFRrmyX2RZWf4k7FP",
        signer: "z1VQizXhZcU7W4JyPmg33FLNMEGbB8xtKHu",
        type: "ED25519",
      },
    ],
    specVersion: "1.2.1",
    timeout: { start: 60 },
    title: "薪资助手",
    version: "0.1.1",
    stats: { downloads: 34 },
    category: {
      name: "productivity",
      locales: { zh: "生产工具", en: "Productivity" },
      _id: "Rke1R5ffuAuDhZJ6",
      createdAt: "2022-01-11T01:48:16.351Z",
      updatedAt: "2022-01-11T01:48:16.351Z",
    },
    owner: {
      did: "z1gShFYDsiMfGtaerBTh2ydu75768xMYPQU",
      name: "nate",
      role: "guest",
    },
    lastPublishedAt: "2022-02-05T07:30:55.178Z",
  },
  {
    author: { email: "lipeng@arcblock.io", name: "lipeng" },
    capabilities: { clusterMode: false },
    children: [],
    community: "",
    description:
      "Provider based on Blocklet Server is used to verify applications by switch wallet",
    did: "z8ia2a9WXPTtbhedVaihXhKBJucCeyuuTx7v1",
    dist: {
      integrity:
        "sha512-6GswHl2h2Xr+aINlKOdaxRUqFnxXycXG1OU56hGyUtjRlD1uPiuxB38SqVE9BB82iQrRFFNnFss09cwuWVTRAg==",
      tarball: "wallet-provider-1.2.0.tgz",
    },
    documentation: "",
    environments: [
      {
        default:
          "https://web.abtwallet.io/,https://wallet.staging.arcblock.io/",
        description: "wallet provider list",
        name: "WALLET_PROVIDERS",
        required: false,
        secure: false,
      },
    ],
    files: ["logo.png", "README.md", "blocklet.md", "screenshots"],
    gitHash: "9ba7de7b240a929b5aac3b8e2b47a94d6da00fc3",
    group: "static",
    homepage: "",
    interfaces: [
      {
        name: "publicUrl",
        path: "/",
        port: "BLOCKLET_PORT",
        prefix: "*",
        protocol: "http",
        type: "web",
      },
    ],
    keywords: ["blocklet", "react"],
    license: "",
    logo: "logo.png",
    main: "build",
    name: "wallet-provider",
    nftFactory: "",
    path: "/static/wallet-provider",
    payment: { price: [], share: [] },
    repository: {
      type: "git",
      url: "git+ssh://git@github.com/blocklet/wallet-provider.git",
    },
    requirements: { abtnode: ">=1.4.0", cpu: "*", os: "*" },
    screenshots: [
      "3-install-list.png",
      "5-mount.png",
      "6-visit.png",
      "1-add.png",
    ],
    scripts: { dev: "npm run start" },
    signatures: [
      {
        type: "ED25519",
        name: "Blocklet Store",
        signer: "zNKXtdqz6Jbw5mKpojK2nP5gRNiEGJY3mNFF",
        pk: "z8VahoQa6oS63Ym3rfsmzZEt9Moonbg4JSUiit5J7DRAV",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-01-13T04:25:49.322Z",
        sig: "z35uXUjVXcEyWv5m9NZQYVfW2b3SVqh8FHZN4opZZw2UT8mj56XAYcn6E2kHvSDeCmPzpycGiRYG1wJCLGkoKutRj",
      },
      {
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-01-13T04:25:46.707Z",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        name: "wallet-provider",
        pk: "z2eCsEyycLQPvqCRxvGBawGwyTfoZF1UpzocGqvtjdx7J",
        signer: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
        type: "ED25519",
        sig: "ztjBNazHTg3wHT45R4NA8pCimXeqhzN9zSJLvvyMqhumSahvPqq3KJjnw3GsvegbGmNbssc49FH1DMBkEctu2U46",
      },
      {
        created: "2022-01-13T04:24:36.738Z",
        name: "wallet-provider",
        pk: "z75CxPgkoiANhn1iCMRHQX2w6fSQPgi2qZiqbhQuy9Xo3",
        sig: "z5hvP1G61vfpTxnAUr8RSTno3adzq5mLpt1Mu4fm1TZLedsmstigX2g1AHYbGUGdcPdxew3nU6SPomzmrSzYXxUxm",
        signer: "z1Rq9qSoqvAq1NcJJTzKB1AnM991Cm4JrzW",
        type: "ED25519",
      },
    ],
    specVersion: "1.2.1",
    timeout: { start: 60 },
    title: "Wallet Provider",
    version: "1.2.0",
    stats: { downloads: 58 },
    category: {
      name: "developer-tools",
      locales: { en: "Developer Tools", zh: "开发者工具" },
      _id: "UXLwYKl1wa1qAhVe",
      createdAt: "2022-01-11T01:48:16.351Z",
      updatedAt: "2022-01-11T01:48:45.576Z",
    },
    owner: {
      did: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
      name: "arcblock",
      role: "admin",
    },
    lastPublishedAt: "2022-01-13T04:25:49.332Z",
  },
  {
    author: { email: "wangqi@arcblock.io", name: "wangqi" },
    capabilities: { clusterMode: false },
    children: [],
    community: "",
    description:
      "A static dapp that supports connecting to any graphql endpoint",
    did: "z8iZpNnc48qcmdMYtvnHFQqroFikNG1AVTmfC",
    dist: {
      integrity:
        "sha512-ZbvpczCICSTARFekTtl/auuRxtldBPXPwO0kSIkjCdPYeBKhH82AeBtWYPyxrmnb/C/tYd4Ibu7P8xXMEFWfVA==",
      tarball: "graphql-playground-1.0.4.tgz",
    },
    documentation: "",
    environments: [],
    files: ["logo.png", "README.md", "blocklet.md", "screenshots"],
    gitHash: "212e9615c94f7f6b246c6f6ff69fab083c08fb52",
    group: "static",
    homepage: "",
    interfaces: [
      {
        name: "publicUrl",
        path: "/",
        port: "BLOCKLET_PORT",
        prefix: "*",
        protocol: "http",
        type: "web",
      },
    ],
    keywords: ["blocklet", "react"],
    license: "",
    logo: "logo.png",
    main: "build",
    name: "graphql-playground",
    nftFactory: "",
    path: "/static/graphql-playground",
    payment: { price: [], share: [] },
    repository: {
      type: "git",
      url: "git+https://github.com/blocklet/graphql-playground.git",
    },
    requirements: { abtnode: ">=1.4.0", cpu: "*", os: "*" },
    screenshots: ["0-home.png", "1-docs.png", "2-history.png"],
    scripts: { dev: "npm run start" },
    signatures: [
      {
        type: "ED25519",
        name: "Blocklet Store",
        signer: "zNKXtdqz6Jbw5mKpojK2nP5gRNiEGJY3mNFF",
        pk: "z8VahoQa6oS63Ym3rfsmzZEt9Moonbg4JSUiit5J7DRAV",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-01-12T09:05:55.489Z",
        sig: "z4t6S8fRvsAc2jY73SrnVAmjMjnB6U4zmTv1fLwLUJM7SkxttruqG3fEzRSTvt1RX78YPLQRd9Wf5si1FFteQMgr8",
      },
      {
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-01-12T09:05:53.083Z",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        name: "graphql-playground",
        pk: "z2eCsEyycLQPvqCRxvGBawGwyTfoZF1UpzocGqvtjdx7J",
        signer: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
        type: "ED25519",
        sig: "z545ttx3T3N1jfkwAcXfKfeHJddyrDDc4Vby5nAmWW9NGhmTRyrpwot3CKqoKQYxQzFz7biBxqi4Kqm1Lc2mSjsak",
      },
      {
        created: "2022-01-12T02:57:31.829Z",
        name: "graphql-playground",
        pk: "z75CxPgkoiANhn1iCMRHQX2w6fSQPgi2qZiqbhQuy9Xo3",
        sig: "z3SDsqnVsa9YsL8mWyjJwwJHs1kERTfqpw8KnL8KWURGFag3d9ZkUfdiMnXPxef6qje81SgqRWFX5QeiN3kXjk3kp",
        signer: "z1Rq9qSoqvAq1NcJJTzKB1AnM991Cm4JrzW",
        type: "ED25519",
      },
    ],
    specVersion: "1.2.1",
    timeout: { start: 60 },
    title: "GraphQL Playground",
    version: "1.0.4",
    stats: { downloads: 56 },
    category: {
      name: "developer-tools",
      locales: { en: "Developer Tools", zh: "开发者工具" },
      _id: "UXLwYKl1wa1qAhVe",
      createdAt: "2022-01-11T01:48:16.351Z",
      updatedAt: "2022-01-11T01:48:45.576Z",
    },
    owner: {
      did: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
      name: "arcblock",
      role: "admin",
    },
    lastPublishedAt: "2022-01-12T02:57:33.146Z",
  },
  {
    author: { email: "engineer@arcblock.io", name: "arcblock" },
    capabilities: { clusterMode: false },
    children: [],
    community: "",
    description: "Ethereum Layer2 & Rollup Solution by ArcBlock",
    did: "z8iZqeUACK955YaBWqEd8aKg3tTki1GpvE2Wu",
    dist: {
      integrity:
        "sha512-e7PHLv+Xvkyjexn5L1eyR75IhyKvUJa98/+Zf67qsuXa0qgNHaZSlMP5rbZg57Uo7tehVa57CfyR1kT2E7jflA==",
      tarball: "did-rollup-1.2.31.tgz",
    },
    documentation: "",
    environments: [
      {
        default: "",
        description: "OCAP chain host",
        name: "CHAIN_HOST",
        required: true,
        secure: false,
      },
      {
        default: "",
        description: "Foreign chain host",
        name: "FOREIGN_CHAIN_HOST",
        required: true,
        secure: false,
      },
      {
        default: "eth",
        description: "Blocklet wallet type must be set to eth",
        name: "BLOCKLET_WALLET_TYPE",
        required: true,
        secure: false,
      },
      {
        default: "",
        description:
          "Send important activities to the webhook, currently only slack is supported",
        name: "INTEGRATION_WEBHOOK",
        required: false,
        secure: true,
      },
    ],
    files: [
      "build",
      "logo.png",
      "README.md",
      "blocklet.md",
      "screenshots",
      "migration/*.js",
      "server/hooks/pre-start.js",
    ],
    gitHash: "f7108a0c3bf439ead3dbc59507a23f874aa842f4",
    group: "dapp",
    homepage: "",
    interfaces: [
      {
        name: "publicUrl",
        path: "/",
        port: "BLOCKLET_PORT",
        prefix: "*",
        protocol: "http",
        services: [
          {
            config: {
              blockUnauthenticated: true,
              ignoreUrls: ["/api/**"],
              invitedUserOnly: "not-first",
            },
            name: "@abtnode/auth-service",
          },
        ],
        type: "web",
      },
    ],
    keywords: ["blocklet", "react"],
    license: "",
    logo: "logo.png",
    main: "blocklet.zip",
    name: "did-rollup",
    nftFactory: "",
    path: "/dapp/did-rollup",
    payment: { price: [], share: [] },
    repository: {
      type: "git",
      url: "git+https://github.com/blocklet/arc-bridge.git",
    },
    requirements: { abtnode: ">=1.4.0", cpu: "*", os: "*" },
    screenshots: ["0-dashboard.png", "1-jobs.png", "2-stake.png"],
    scripts: {
      dev: "npm run start",
      preStart: "node server/hooks/pre-start.js",
    },
    signatures: [
      {
        type: "ED25519",
        name: "Blocklet Store",
        signer: "zNKXtdqz6Jbw5mKpojK2nP5gRNiEGJY3mNFF",
        pk: "z8VahoQa6oS63Ym3rfsmzZEt9Moonbg4JSUiit5J7DRAV",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-02-08T13:47:14.484Z",
        sig: "z4Rwns2AZuKRGGjLwXSssuKvZddAP44P4RDLrPwFraVGoToNX3Piekr4VbwcTTfkH6LLefvQeko5vMjGvZGftJzHF",
      },
      {
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-02-08T13:47:13.396Z",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        name: "did-rollup",
        pk: "z2eCsEyycLQPvqCRxvGBawGwyTfoZF1UpzocGqvtjdx7J",
        signer: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
        type: "ED25519",
        sig: "z4gTc5jEu5CB5wA81wByusdCmLsiCcuMcAUutqQzUEEpC52B6gwiPkbWnCVS7dqDrhw1nNdbXTnwks8jAwxpvUYTR",
      },
      {
        created: "2022-02-08T12:51:06.843Z",
        name: "did-rollup",
        pk: "z75CxPgkoiANhn1iCMRHQX2w6fSQPgi2qZiqbhQuy9Xo3",
        sig: "zPw1Vsp65FUeuT9E19Fqdx4bDjsXCUJGn2Fm6mN61XTK4tynGvZZkwCevWWXwuNmeHUxo4DnNtUayMnW4GyNULMB",
        signer: "z1Rq9qSoqvAq1NcJJTzKB1AnM991Cm4JrzW",
        type: "ED25519",
      },
    ],
    specVersion: "1.2.1",
    timeout: { start: 60 },
    title: "ArcBridge Node",
    version: "1.2.31",
    stats: { downloads: 317 },
    category: {
      name: "blockchain",
      locales: { zh: "区块链", en: "Blockchain" },
      _id: "ehbHn3Ceu9UQHRtQ",
      createdAt: "2022-01-11T01:49:44.009Z",
      updatedAt: "2022-01-11T01:49:44.009Z",
    },
    owner: {
      did: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
      name: "arcblock",
      role: "admin",
    },
    lastPublishedAt: "2022-02-08T13:47:14.504Z",
  },
  {
    author: { email: "zhanghan@arcblock.io", name: "zhanghan" },
    capabilities: { clusterMode: false },
    children: [],
    community: "https://community.arcblockio.cn",
    description: "A simple NFT Store",
    did: "z8iZqkCjLP6TZpR12tT3jESWxB8SGzNsx8nZa",
    dist: {
      integrity:
        "sha512-zQ7oc3NyPBpg4ux1EHQHHI3guGV6uC+guZIV3J/RlUdDa/KQ0YR3nyUdjOZZZ9AeWMboXsOlVNRL8FNO9j7t4A==",
      tarball: "nft-store-0.5.38.tgz",
    },
    documentation: "",
    environments: [
      {
        default: "",
        description: "Please provide endpoint of chain",
        name: "CHAIN_HOST",
        required: true,
        secure: false,
      },
      {
        default: "",
        description: "Please provide factory owner of factory list",
        name: "FACTORY_OWNER_DID",
        required: false,
        secure: false,
      },
      {
        default: "",
        description:
          "Hide some factory, they will not show in the factory list page (Use ',' as separator if there are multiple values)",
        name: "DISABLED_FACTORY_ADDRESS",
        required: false,
        secure: false,
      },
      {
        default: "",
        description: "Get a config object to set nft-store for a url",
        name: "CONFIG_API",
        required: false,
        secure: false,
      },
      {
        default: "",
        description: "Home path of the application",
        name: "HOME_PATH",
        required: false,
        secure: false,
      },
    ],
    files: [
      "screenshots",
      "server/hooks/pre-start.js",
      "logo.png",
      "blocklet.md",
      "README.md",
      "build",
    ],
    gitHash: "e561cb092e418281fbe37feb2995c49e71770842",
    group: "dapp",
    homepage: "",
    interfaces: [
      {
        name: "publicUrl",
        path: "/",
        port: "BLOCKLET_PORT",
        prefix: "*",
        protocol: "tcp",
        services: [
          {
            config: { blockUnauthenticated: false },
            name: "@abtnode/auth-service",
          },
        ],
        type: "web",
      },
    ],
    keywords: ["dapp", "nft", "store"],
    license: "Apache-2.0",
    logo: "logo.png",
    main: "blocklet.zip",
    name: "nft-store",
    nftFactory: "",
    path: "/dapp/nft-store",
    payment: { price: [], share: [] },
    repository: {
      type: "git",
      url: "git+https://github.com/Blocklet/nft-store.git",
    },
    requirements: { abtnode: ">=1.2.3", cpu: "*", os: "*" },
    screenshots: [
      "screenshot-0.png",
      "screenshot-1.png",
      "screenshot-2.png",
      "screenshot-3.png",
    ],
    scripts: {
      dev: "npm run start",
      preStart: "node server/hooks/pre-start.js",
    },
    signatures: [
      {
        type: "ED25519",
        name: "Blocklet Store",
        signer: "zNKXtdqz6Jbw5mKpojK2nP5gRNiEGJY3mNFF",
        pk: "z8VahoQa6oS63Ym3rfsmzZEt9Moonbg4JSUiit5J7DRAV",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-01-27T01:57:53.665Z",
        sig: "z3AiuCkhXTV87Hpnd68RcQC9aoFizdk3zfnMKkVWBo93xSmXBW3zaS3KdXxaLsbnbjbLoTjyP9mVTHHekX6UJrz68",
      },
      {
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-01-27T01:57:52.374Z",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        name: "nft-store",
        pk: "z2eCsEyycLQPvqCRxvGBawGwyTfoZF1UpzocGqvtjdx7J",
        signer: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
        type: "ED25519",
        sig: "z2uk48GMxsVSoyamRf8PL6MauLm89dhzn1bmsKaGy7qZDpYgU4iPmKXpVxMKUPDM8gsRP3r8gmhWT1EZn15euyRaJ",
      },
      {
        created: "2022-01-27T01:43:49.220Z",
        name: "nft-store",
        pk: "z75CxPgkoiANhn1iCMRHQX2w6fSQPgi2qZiqbhQuy9Xo3",
        sig: "z53uw7jSXoZXagNSUXfiYAKnqrdhPS742j8rrhCaCUPBASq3qmtFhADG7vrhAcQqyXD1URFvqrDtePeshaJgVho34",
        signer: "z1Rq9qSoqvAq1NcJJTzKB1AnM991Cm4JrzW",
        type: "ED25519",
      },
    ],
    specVersion: "1.2.1",
    timeout: { start: 30 },
    title: "NFT Store",
    version: "0.5.38",
    stats: { downloads: 3642 },
    category: {
      name: "shopping",
      locales: { zh: "购物", en: "Shopping" },
      _id: "ZQS3G72gIY02XUsD",
      createdAt: "2022-01-11T01:48:16.351Z",
      updatedAt: "2022-01-11T01:48:16.351Z",
    },
    owner: {
      did: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
      name: "arcblock",
      role: "admin",
    },
    lastPublishedAt: "2022-01-27T01:57:53.679Z",
  },
  {
    author: { email: "paper@arcblock.io", name: "paper" },
    capabilities: { clusterMode: false },
    children: [],
    community: "https://community.arcblockio.cn",
    description: "A sort of API for user to query ERC20 fiat price",
    did: "z8iZnxpWdP8jMNDhZSJ2SPg3Lg9Yh6rGMEard",
    dist: {
      integrity:
        "sha512-RrjKNok5ygBafGDRQFDa8krvExlYbrM/0yuaPdTuIqM8bmN/yxHb7kx/w9FpW7l1C5FImSFKvwODUGGjV5nMbA==",
      tarball: "token-data-2.3.0.tgz",
    },
    documentation: "https://docs.arcblock.io",
    environments: [
      {
        default: "",
        description: "Crypto Market Cap API Key",
        name: "CMC_KEY",
        required: true,
        secure: true,
      },
      {
        default: "",
        description: "INFURA API Key",
        name: "INFURA_KEY",
        required: true,
        secure: true,
      },
      {
        default: "",
        description: "ETHERSCAN API Key",
        name: "ETHERSCAN_KEY",
        required: true,
        secure: true,
      },
      {
        default: "false",
        description: "refresh DB token list",
        name: "NEED_REFRESH_TOKEN",
        required: false,
        secure: false,
      },
      {
        default: "",
        description: "web hook to slack",
        name: "SLACK_WEBHOOK",
        required: false,
        secure: false,
      },
      {
        default: "false",
        description: "allow external user to access",
        name: "ALLOW_EXTERNAL",
        required: false,
        secure: false,
      },
    ],
    files: [
      "screenshots",
      "public",
      "logo.png",
      "blocklet.md",
      "README.md",
      "build",
    ],
    gitHash: "23dc26da4b3e1186a052399b501c0ad97b6253be",
    group: "dapp",
    homepage: "https://github.com/blocklet/token-data",
    interfaces: [
      {
        name: "publicUrl",
        path: "/",
        port: "BLOCKLET_PORT",
        prefix: "*",
        protocol: "http",
        services: [
          {
            config: {
              blockUnauthenticated: true,
              ignoreUrls: ["/api/**", "/"],
            },
            name: "@abtnode/auth-service",
          },
        ],
        type: "web",
      },
    ],
    keywords: ["blocklet", "registry"],
    license: "Apache-2.0",
    logo: "logo.png",
    main: "blocklet.zip",
    name: "token-data",
    nftFactory: "",
    path: "/dapp/token-data",
    payment: { price: [], share: [] },
    repository: {
      type: "git",
      url: "git+ssh://git@github.com/blocklet/token-data.git",
    },
    requirements: { abtnode: ">=1.2.6", cpu: "*", os: "*" },
    screenshots: ["list.png", "api.png"],
    scripts: { dev: "npm run start" },
    signatures: [
      {
        type: "ED25519",
        name: "Blocklet Store",
        signer: "zNKXtdqz6Jbw5mKpojK2nP5gRNiEGJY3mNFF",
        pk: "z8VahoQa6oS63Ym3rfsmzZEt9Moonbg4JSUiit5J7DRAV",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-02-10T03:18:12.845Z",
        sig: "z5ov7HJbxd9frKixTkSwnbFs3sxjNQtuDCBfjGrpXwFBpiBvm9VimJqwGxegNoVBUZQZdU5KShzsWynWKbDuy9xY1",
      },
      {
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-02-10T03:18:11.600Z",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        name: "token-data",
        pk: "z2eCsEyycLQPvqCRxvGBawGwyTfoZF1UpzocGqvtjdx7J",
        signer: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
        type: "ED25519",
        sig: "z3xuX5FatR5bZWCTcrSybn9d8UEM3ihePYYTVjh7YouZgTJ9u5jvZNqSUKkqj5A2CRvvHUFGzbAkbdVEcrjCQgbuQ",
      },
      {
        created: "2022-02-09T07:01:25.827Z",
        name: "token-data",
        pk: "z75CxPgkoiANhn1iCMRHQX2w6fSQPgi2qZiqbhQuy9Xo3",
        sig: "z3h8yjUxwDtPUQh1W9Ka9xLrpcyxgn1EGeyxjxPvwFkTfaMCrpxZLvhXwynhfok2CCXU84otHmH2q6zW6ML5474w1",
        signer: "z1Rq9qSoqvAq1NcJJTzKB1AnM991Cm4JrzW",
        type: "ED25519",
      },
    ],
    specVersion: "1.2.1",
    support: "support@arcblock.io",
    timeout: { start: 60 },
    title: "Token Data",
    version: "2.3.0",
    stats: { downloads: 77 },
    category: {
      name: "blockchain",
      locales: { zh: "区块链", en: "Blockchain" },
      _id: "ehbHn3Ceu9UQHRtQ",
      createdAt: "2022-01-11T01:49:44.009Z",
      updatedAt: "2022-01-11T01:49:44.009Z",
    },
    owner: {
      did: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
      name: "arcblock",
      role: "admin",
    },
    lastPublishedAt: "2022-02-10T03:18:12.854Z",
  },
  {
    author: { name: "wangshijun" },
    capabilities: { clusterMode: false },
    children: [],
    community: "",
    description:
      "A simple coming soon page implementation that can be used to serve sites that are under construction",
    did: "z8ia5AUWNBoc5Jw6Zf2ru97W1y6PZVFiFa7h9",
    dist: {
      integrity:
        "sha512-QCC232lLWS86jt1LfbaFtjcLaccGgLtQ6dmaBmE7iZeikkLl6VaxdyZSo0ySkreNYHiiKUCHNidE6F6lZRBlng==",
      tarball: "coming-soon-page-0.4.2.tgz",
    },
    documentation: "",
    environments: [],
    files: ["blocklet.md", "screenshots"],
    gitHash: "b9f1ee1f886deb64c9366072620e1d59db463773",
    group: "static",
    homepage: "",
    interfaces: [
      {
        name: "publicUrl",
        path: "/",
        port: "BLOCKLET_PORT",
        prefix: "*",
        protocol: "http",
        type: "web",
      },
    ],
    keywords: ["demo", "blocklet"],
    license: "",
    logo: "logo.png",
    main: "app",
    name: "coming-soon-page",
    nftFactory: "",
    path: "/static/coming-soon-page",
    payment: { price: [], share: [] },
    requirements: { abtnode: ">=1.2.0", cpu: "*", os: "*" },
    screenshots: ["home.png"],
    signatures: [
      {
        type: "ED25519",
        name: "Blocklet Store",
        signer: "zNKXtdqz6Jbw5mKpojK2nP5gRNiEGJY3mNFF",
        pk: "z8VahoQa6oS63Ym3rfsmzZEt9Moonbg4JSUiit5J7DRAV",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2021-12-29T02:01:29.363Z",
        sig: "z3XMbyYw2GCxqJgZAW38mfndEtvJwBfRPSKHjm7VCAWAb3Xy6T4sKeYTzjKsiAjNzgzcYaAS6amu4ey3Ly2nTbPMY",
      },
      {
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2021-12-29T02:01:24.868Z",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        name: "coming-soon-page",
        pk: "z2eCsEyycLQPvqCRxvGBawGwyTfoZF1UpzocGqvtjdx7J",
        signer: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
        type: "ED25519",
        sig: "z2gQjdCLGuEEN3VMxDgm5NkdrD8n8ktQGJgeLgo8X1WyWrMRB5xFBPG7fRuYdJKM6LDowCMUJxu9yu95P8XDAPCm3",
      },
      {
        created: "2021-12-28T13:24:44.807Z",
        name: "coming-soon-page",
        pk: "z75CxPgkoiANhn1iCMRHQX2w6fSQPgi2qZiqbhQuy9Xo3",
        sig: "z5WDDFz3P1iFSiwJvSu5Ei1FW9Wb7vzoh8RKwMmoopSvYuTYKnzQWbJ1R8Mdzv9M8xnZdku5jMEV1DogvVKCFjJkJ",
        signer: "z1Rq9qSoqvAq1NcJJTzKB1AnM991Cm4JrzW",
        type: "ED25519",
      },
    ],
    specVersion: "1.2.0",
    timeout: { start: 60 },
    title: "Coming Soon Page",
    version: "0.4.2",
    stats: { downloads: 387 },
    category: {
      name: "blog",
      locales: { zh: "博客", en: "Blog" },
      _id: "moa7XOIdvLpI3m49",
      createdAt: "2022-01-11T01:48:16.351Z",
      updatedAt: "2022-01-11T01:48:16.351Z",
    },
    owner: {
      did: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
      name: "arcblock",
      role: "admin",
    },
    lastPublishedAt: "2021-12-28T13:24:46.153Z",
  },
  {
    author: { email: "shijun@arcblock.io", name: "shijun" },
    capabilities: { clusterMode: false },
    children: [],
    community: "https://community.arcblockio.cn",
    description: "Marketplace to buy and sell NFT on ABT Network",
    did: "z8iZvmERrWxqReWe1HZmkAaZvFeRpkXutfKDk",
    dist: {
      integrity:
        "sha512-2d8BVvRW7VtAY+kDYq9wg9MmPWGQG4aP6Mb5rdSEXfVKRrMUl/x8HTHp5WBDrNPOeOXZ7yjC3JjFCFx0+0FKTA==",
      tarball: "nft-marketplace-0.6.24.tgz",
    },
    documentation: "https://docs.arcblock.io",
    environments: [
      {
        default: "https://beta.abtnetwork.io/api/",
        description: "What's endpoint of the chain?",
        name: "CHAIN_HOST",
        required: true,
        secure: false,
      },
      {
        default: "z35n6UoHSi9MED4uaQy6ozFgKPaZj2UKrurBG",
        description: "Which token does this marketplace accept as payment?",
        name: "PAYMENT_TOKEN_ID",
        required: true,
        secure: false,
      },
      {
        default: "0.02",
        description: "How much the marketplace will preserve on deal?",
        name: "DEAL_FEE_RATIO",
        required: true,
        secure: false,
      },
      {
        default: "30",
        description: "How long to wait in minutes before consider a bid final?",
        name: "DEAL_DELAY_SINCE_LAST_BID",
        required: true,
        secure: false,
      },
      {
        default: "",
        description: "Tags allowed when list auction?",
        name: "ALLOWED_TAGS",
        required: false,
        secure: false,
      },
      {
        default: "1",
        description: "Price step in bid auction",
        name: "PRICE_STEP",
        required: true,
        secure: false,
      },
      {
        default: "1",
        description: "Min bid delta amount in bid auction",
        name: "MIN_BID_DELTA_AMOUNT",
        required: true,
        secure: false,
      },
      {
        default: "",
        description: "Google Analytics measurement id",
        name: "GOOGLE_ANALYTICS_ID",
        required: false,
        secure: false,
      },
    ],
    files: [
      "screenshots",
      "public",
      "logo.png",
      "blocklet.md",
      "README.md",
      "build",
      "api/hooks/pre-start.js",
    ],
    gitHash: "721873e5b08fdd8b81cd852e886f838fac28be23",
    group: "dapp",
    homepage: "https://github.com/blocklet/nft-marketplace",
    interfaces: [
      {
        name: "publicUrl",
        path: "/",
        port: "BLOCKLET_PORT",
        prefix: "*",
        protocol: "http",
        services: [
          {
            config: { blockUnauthenticated: false },
            name: "@abtnode/auth-service",
          },
        ],
        type: "web",
      },
    ],
    keywords: ["nft", "marketplace"],
    license: "Apache-2.0",
    logo: "logo.png",
    main: "blocklet.zip",
    name: "nft-marketplace",
    nftFactory: "",
    path: "/dapp/nft-marketplace",
    payment: { price: [], share: [] },
    repository: {
      type: "git",
      url: "git+https://github.com/blocklet/nft-marketplace.git",
    },
    requirements: { abtnode: ">=1.3.12", cpu: "*", os: "*" },
    screenshots: ["0-list.png", "1-detail.png", "2-detail-bidding.png"],
    scripts: { dev: "npm run start", preStart: "node api/hooks/pre-start.js" },
    signatures: [
      {
        type: "ED25519",
        name: "Blocklet Store",
        signer: "zNKXtdqz6Jbw5mKpojK2nP5gRNiEGJY3mNFF",
        pk: "z8VahoQa6oS63Ym3rfsmzZEt9Moonbg4JSUiit5J7DRAV",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-01-29T00:59:36.201Z",
        sig: "z4QSHqyq48GpJEJBJJCqoNTLgQTp8BoZ2C2XgGqit2jnvVkbdq7qSnJX6NgurcbUk1LjBxKgmqFoP31kURrNg9rA5",
      },
      {
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-01-29T00:59:30.315Z",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        name: "nft-marketplace",
        pk: "z2eCsEyycLQPvqCRxvGBawGwyTfoZF1UpzocGqvtjdx7J",
        signer: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
        type: "ED25519",
        sig: "z3F3thqspg8P51ycGsUyiTCDFXh23gsJCpiVuuxu8XKMP91ffZkPPETjpx8KhgaZ41vq5VRnPT5RLPVBsUtsPwZ26",
      },
      {
        created: "2022-01-29T00:55:33.083Z",
        name: "nft-marketplace",
        pk: "z75CxPgkoiANhn1iCMRHQX2w6fSQPgi2qZiqbhQuy9Xo3",
        sig: "zfD86feiiKq17ABMmZqFHHgyJWayxGW8V3xRk3Zc1xrYXqUeu4AFvZTupguHD9gAs5rz7VqZxJsKkhkPz2aqA4bS",
        signer: "z1Rq9qSoqvAq1NcJJTzKB1AnM991Cm4JrzW",
        type: "ED25519",
      },
    ],
    specVersion: "1.2.1",
    support: "support@arcblock.io",
    timeout: { start: 60 },
    title: "NFT Marketplace",
    version: "0.6.24",
    stats: { downloads: 70 },
    category: {
      name: "shopping",
      locales: { zh: "购物", en: "Shopping" },
      _id: "ZQS3G72gIY02XUsD",
      createdAt: "2022-01-11T01:48:16.351Z",
      updatedAt: "2022-01-11T01:48:16.351Z",
    },
    owner: {
      did: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
      name: "arcblock",
      role: "admin",
    },
    lastPublishedAt: "2022-01-29T00:59:36.220Z",
  },
  {
    author: { email: "shijun@arcblock.io", name: "shijun" },
    capabilities: { clusterMode: false },
    children: [],
    community: "https://community.arcblockio.cn",
    description:
      "A faucet to help users to get test token on arcblock blockchain network",
    did: "z8iZzjfRix3FewZbMxNwcRp1TdUBa32VoLtps",
    dist: {
      integrity:
        "sha512-C6wz7w1msVWTnsdipAKl+jczr6wq8UV6U2PxKtsX/UovTAGlP/sJFthNY6I3qw36+GgVJrWQ3iZexqibng6oNg==",
      tarball: "faucet-webapp-0.2.17.tgz",
    },
    documentation: "https://docs.arcblock.io",
    environments: [],
    files: [
      "screenshots",
      "public",
      "logo.png",
      "blocklet.md",
      "README.md",
      "build",
    ],
    gitHash: "69a0f3aa7e6cbede25589bad5cd7eec22277681f",
    group: "dapp",
    homepage: "https://github.com/blocklet/faucet-webapp",
    interfaces: [
      {
        name: "publicUrl",
        path: "/",
        port: "BLOCKLET_PORT",
        prefix: "*",
        protocol: "http",
        type: "web",
      },
    ],
    keywords: ["blocklet", "registry"],
    license: "Apache-2.0",
    logo: "logo.png",
    main: "blocklet.zip",
    name: "faucet-webapp",
    nftFactory: "",
    path: "/dapp/faucet-webapp",
    payment: { price: [], share: [] },
    repository: {
      type: "git",
      url: "git+https://github.com/blocklet/faucet-webapp.git",
    },
    requirements: { abtnode: ">=1.2.6", cpu: "*", os: "*" },
    screenshots: ["add.png", "claim.png", "donate.png", "list.png"],
    scripts: { dev: "npm run start" },
    signatures: [
      {
        type: "ED25519",
        name: "Blocklet Store",
        signer: "zNKXtdqz6Jbw5mKpojK2nP5gRNiEGJY3mNFF",
        pk: "z8VahoQa6oS63Ym3rfsmzZEt9Moonbg4JSUiit5J7DRAV",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-01-14T06:43:49.264Z",
        sig: "zeWDRZrmdkdSqmrhqmP8HKhWMLx7wG4eQ9cvbSYwmKRS1P3QDTB7heQnA3AfNTcF3jaEj66grXFnA1H5JGW9SXzb",
      },
      {
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-01-14T06:43:47.370Z",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        name: "faucet-webapp",
        pk: "z2eCsEyycLQPvqCRxvGBawGwyTfoZF1UpzocGqvtjdx7J",
        signer: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
        type: "ED25519",
        sig: "z3onPf4qdwhSoq9TTjM7SDjVPftGaBHeCxSPd36ny6KH7PJVVcVm15TFDqP2S1ippNNL6JaDbL9Ytgg31q1CCZY62",
      },
      {
        created: "2022-01-13T07:05:03.617Z",
        name: "faucet-webapp",
        pk: "z75CxPgkoiANhn1iCMRHQX2w6fSQPgi2qZiqbhQuy9Xo3",
        sig: "z29ErvDZwgqxotUMEtcraoE35s9kLK6qkBpKFf9HAV5PdTj42VPdaMQpLhzA1VADRiuTERYUma4CTWW5cpNTa3AQn",
        signer: "z1Rq9qSoqvAq1NcJJTzKB1AnM991Cm4JrzW",
        type: "ED25519",
      },
    ],
    specVersion: "1.2.1",
    support: "support@arcblock.io",
    timeout: { start: 60 },
    title: "ABT Network Faucet",
    version: "0.2.17",
    stats: { downloads: 65 },
    category: {
      name: "developer-tools",
      locales: { en: "Developer Tools", zh: "开发者工具" },
      _id: "UXLwYKl1wa1qAhVe",
      createdAt: "2022-01-11T01:48:16.351Z",
      updatedAt: "2022-01-11T01:48:45.576Z",
    },
    owner: {
      did: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
      name: "arcblock",
      role: "admin",
    },
    lastPublishedAt: "2022-01-14T06:43:49.274Z",
  },
  {
    author: { email: "shijun@arcblock.io", name: "wangshijun" },
    capabilities: { clusterMode: false, component: true },
    children: [
      {
        mountPoints: [
          {
            child: { interfaceName: "publicUrl" },
            root: { interfaceName: "publicUrl", prefix: "/promotion-tool" },
          },
        ],
        name: "promotion-tool",
        resolved:
          "https://dev.store.blocklet.dev/api/blocklets/z8iZk7PZ3guu3biYGUJRYpAwRnMZkvQ1ENA1z/blocklet.json",
      },
    ],
    community: "https://community.arcblockio.cn",
    description:
      "A simple playground that shows the potential of OCAP powered blockchain and DID Wallet V2",
    did: "z8iZjySpAu4jzbMochL9k1okuji1GcS7RRRDM",
    dist: {
      integrity:
        "sha512-fSyqbuE3/HufMIryRStAXNH0DhGWwEvPyy3OjwS48mg7PYWxq6Xp4cmCtvu4ApOZQz8NBtOWI3GgZrk3M5wRWA==",
      tarball: "ocap-playground-0.24.12.tgz",
    },
    documentation: "",
    environments: [
      {
        default: "https://beta.abtnetwork.io/api/",
        description: "Please provide endpoint of local chain",
        name: "CHAIN_HOST",
        required: true,
        secure: false,
      },
      {
        default: "z35n6UoHSi9MED4uaQy6ozFgKPaZj2UKrurBG",
        description: "Please provide local token for the playground",
        name: "LOCAL_TOKEN_ID",
        required: true,
        secure: false,
      },
      {
        default: "z35n3WVTnN7KrR4gXn3szR6oneVefkBBx78Fc",
        description: "Please provide foreign token for the playground",
        name: "FOREIGN_TOKEN_ID",
        required: true,
        secure: false,
      },
    ],
    files: [
      "api/libs/hooks/pre-start.js",
      "screenshots",
      "logo.png",
      "blocklet.md",
      "README.md",
      "build",
    ],
    gitHash: "0abafb692a37e31df4ea7a091ebc0b612a9b5373",
    group: "dapp",
    homepage: "",
    interfaces: [
      {
        name: "publicUrl",
        path: "/",
        port: "BLOCKLET_PORT",
        prefix: "*",
        protocol: "tcp",
        services: [
          {
            config: {
              ignoreUrls: [
                "/api/did/**",
                "/api/agent/**",
                "/api/nft/**",
                "/blocklet/**",
                "/instance/**",
              ],
            },
            name: "@abtnode/auth-service",
          },
        ],
        type: "web",
      },
    ],
    keywords: ["dapp", "playground", "wallet"],
    license: "Apache-2.0",
    logo: "logo.png",
    main: "blocklet.zip",
    name: "ocap-playground",
    nftFactory: "",
    path: "/dapp/ocap-playground",
    payment: { price: [], share: [] },
    repository: {
      type: "git",
      url: "git+https://github.com/blocklet/ocap-playground.git",
    },
    requirements: { abtnode: ">=1.3.5", cpu: "*", os: "*" },
    screenshots: ["0-home.png", "1-profile.png", "2-everything.png"],
    scripts: {
      dev: "npm run start",
      preStart: "node api/libs/hooks/pre-start.js",
    },
    signatures: [
      {
        type: "ED25519",
        name: "Blocklet Store",
        signer: "zNKXtdqz6Jbw5mKpojK2nP5gRNiEGJY3mNFF",
        pk: "z8VahoQa6oS63Ym3rfsmzZEt9Moonbg4JSUiit5J7DRAV",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-02-16T13:50:13.057Z",
        sig: "z2yQwCKYBdgRZFceQ7hYfk2Udh9mmfVu3JHkHC5ZqnGE4f1igsdETEB2zygJeEewKnQzAk2f5QDPiZUcbHR2BRu8Y",
      },
      {
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-02-16T13:50:07.459Z",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        name: "ocap-playground",
        pk: "z2eCsEyycLQPvqCRxvGBawGwyTfoZF1UpzocGqvtjdx7J",
        signer: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
        type: "ED25519",
        sig: "zZ8y6eqLfu4EdRq4sx7KYkT1T6ScqDsykgVzbjFJWR2PGnU9UyPCkrTbGQAzZY1FRwi5h6pEFFpeP2kv8AVyL39w",
      },
      {
        created: "2022-02-15T03:36:20.351Z",
        name: "ocap-playground",
        pk: "z75CxPgkoiANhn1iCMRHQX2w6fSQPgi2qZiqbhQuy9Xo3",
        sig: "zBLowAcvYs5RMDWdUjb3HU7YpUNrAaNcFjcHS6unMi2o1iKJNaLg7Nub4b7q86t4yXe97djjyAW2UCyUWJS1SgwG",
        signer: "z1Rq9qSoqvAq1NcJJTzKB1AnM991Cm4JrzW",
        type: "ED25519",
      },
    ],
    specVersion: "1.2.1",
    timeout: { start: 15 },
    title: "Wallet Playground",
    version: "0.24.12",
    stats: { downloads: 87 },
    category: {
      name: "developer-tools",
      locales: { en: "Developer Tools", zh: "开发者工具" },
      _id: "UXLwYKl1wa1qAhVe",
      createdAt: "2022-01-11T01:48:16.351Z",
      updatedAt: "2022-01-11T01:48:45.576Z",
    },
    owner: {
      did: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
      name: "arcblock",
      role: "admin",
    },
    lastPublishedAt: "2022-02-16T13:50:13.070Z",
  },
  {
    author: { name: "leermao" },
    capabilities: { clusterMode: false },
    children: [],
    community: "",
    description:
      "Official DID Wallet webapp implementation that makes it possible to manage your digital identities and assets from the browser.",
    did: "z8iZpnScvjjeeyYZQoHSdXm4GQTqcfTTGkyPP",
    dist: {
      integrity:
        "sha512-RNL1Z7Rn/mhKxJHVTcjtHBUvmK/uEiQfxv8iw0rry/TFUWzXHfKP3tVjOvnbykl4YC0+vG8F+LyW0rDC8PAO7g==",
      tarball: "abt-wallet-3.10.0.tgz",
    },
    documentation: "",
    environments: [],
    files: ["blocklet.md", "screenshots", "build", "wallet.png"],
    gitHash: "6558d04c89e7c1abdfd05e7c8931ac2ccc5f91ab",
    group: "static",
    homepage: "",
    interfaces: [
      {
        name: "publicUrl",
        path: "/",
        port: "BLOCKLET_PORT",
        prefix: "/",
        protocol: "tcp",
        type: "web",
      },
    ],
    keywords: ["Wallet"],
    license: "Apache-2.0",
    logo: "wallet.png",
    main: "build",
    name: "abt-wallet",
    nftFactory: "",
    path: "/static/abt-wallet",
    payment: { price: [], share: [] },
    requirements: { abtnode: ">=1.2.5", cpu: "*", os: "*" },
    screenshots: [
      "0-login.png",
      "1-assets.png",
      "2-balance.png",
      "3-txs.png",
      "4-nft.png",
      "5-bridge-move.png",
      "6-move-history.png",
    ],
    scripts: { dev: "npm run start" },
    signatures: [
      {
        type: "ED25519",
        name: "Blocklet Store",
        signer: "zNKXtdqz6Jbw5mKpojK2nP5gRNiEGJY3mNFF",
        pk: "z8VahoQa6oS63Ym3rfsmzZEt9Moonbg4JSUiit5J7DRAV",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-01-25T04:06:10.044Z",
        sig: "z3PRDByqy3njtFJstStTWmmvZkYjkrBj7Ce1ki5bdZxYm2B9tuBMGF3VraFEXgY6TGYEbLDj1aJqUyDnJqu36iVAT",
      },
      {
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-01-25T04:06:08.539Z",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        name: "abt-wallet",
        pk: "z2eCsEyycLQPvqCRxvGBawGwyTfoZF1UpzocGqvtjdx7J",
        signer: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
        type: "ED25519",
        sig: "z2SPE1i4dRuCZbm4LMXmsrgck586ZpkjEbcBfiCoCBSfe6BTGAAqjyXCrP2hBnGbTtjm479LvTkawR2QorHNfWedY",
      },
      {
        created: "2022-01-25T01:41:09.981Z",
        name: "abt-wallet",
        pk: "z75CxPgkoiANhn1iCMRHQX2w6fSQPgi2qZiqbhQuy9Xo3",
        sig: "z5coEs9hceL2as1ydFGdzf6G2zz1an364AH9FhfHhqAFPKrK6XNTXrRCtmLi4ptnBPiaCHCZepjfmQ74mpT4KMbK6",
        signer: "z1Rq9qSoqvAq1NcJJTzKB1AnM991Cm4JrzW",
        type: "ED25519",
      },
    ],
    specVersion: "1.2.1",
    timeout: { start: 10 },
    title: "DID Wallet",
    version: "3.10.0",
    stats: { downloads: 106 },
    category: {
      name: "blockchain",
      locales: { zh: "区块链", en: "Blockchain" },
      _id: "ehbHn3Ceu9UQHRtQ",
      createdAt: "2022-01-11T01:49:44.009Z",
      updatedAt: "2022-01-11T01:49:44.009Z",
    },
    owner: {
      did: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
      name: "arcblock",
      role: "admin",
    },
    lastPublishedAt: "2022-01-25T04:06:10.054Z",
  },
  {
    author: {
      email: "wangshijun2010@gmail.com",
      name: "wangshijun",
      url: "http://github.com/wangshijun",
    },
    capabilities: { clusterMode: true, component: true },
    children: [
      {
        mountPoints: [
          {
            child: { interfaceName: "publicUrl" },
            root: { interfaceName: "publicUrl", prefix: "/api" },
          },
        ],
        name: "@ocap/qldb-chain-api",
        resolved:
          "https://registry.arcblock.io/api/blocklets/z8iZuohP9o6jfKeHgZK1gxke6usvrgK8Vw7B6/blocklet.json",
      },
      {
        mountPoints: [
          {
            child: { interfaceName: "publicUrl" },
            root: { interfaceName: "publicUrl", prefix: "/" },
          },
        ],
        name: "@arcblock/block-explorer",
        resolved:
          "https://registry.arcblock.io/api/blocklets/z8iZyVVn6XsvcuiYhtdw3GoasMbtqR9BjvJz3/blocklet.json",
      },
    ],
    community: "",
    description:
      "Blockchain manager blocklet that combines QLDB chain API and block explorer blocklet",
    did: "z8iZyP8q92ehxgvn93PHyF1euqiP4bXVtryjh",
    dist: {
      integrity:
        "sha512-u3JYxfHDX0Iqazdd5WnvwRn2L3MVD0FLD4fzkhF+VyOu6V2pJyEdP0MVBLA0lqEFxExRQVBHxPSRl2UfcDAMEQ==",
      tarball: "@ocapqldb-chain-manager-1.14.13.tgz",
    },
    documentation: "",
    environments: [
      {
        default: "/api",
        description: "Default chain endpoint of explorer",
        name: "EXPLORER_CHAIN_ENDPOINT",
        required: false,
        secure: false,
      },
    ],
    files: ["blocklet.md", "screenshots/"],
    gitHash: "1d2c6b7d5339ed8b4cd8382812ab943a5770f7d0",
    group: "gateway",
    homepage: "",
    interfaces: [
      {
        name: "publicUrl",
        path: "/",
        port: "BLOCKLET_PORT",
        prefix: "*",
        protocol: "http",
        type: "web",
      },
    ],
    license: "",
    name: "@ocap/qldb-chain-manager",
    nftFactory: "",
    path: "/gateway/@ocap/qldb-chain-manager",
    payment: { price: [], share: [] },
    requirements: { abtnode: ">=1.2.5", cpu: "*", os: "*" },
    screenshots: [
      "0-home.png",
      "1-txs.png",
      "2-account.png",
      "3-asset.png",
      "4-bridge.png",
      "5-bridge-move.png",
      "6-transfer.png",
    ],
    signatures: [
      {
        type: "ED25519",
        name: "Blocklet Store",
        signer: "zNKXtdqz6Jbw5mKpojK2nP5gRNiEGJY3mNFF",
        pk: "z8VahoQa6oS63Ym3rfsmzZEt9Moonbg4JSUiit5J7DRAV",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-02-15T01:54:00.865Z",
        sig: "z5ttzXSsufk5WdrBxNhASGBSAWMtzgz6TCq3D1Et484ikY5Zfsc82pqZyXcCTVeFmRfY7SfcCR1trWV1QD5r1DJhE",
      },
      {
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-02-15T01:53:59.346Z",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        name: "@ocap/qldb-chain-manager",
        pk: "z2eCsEyycLQPvqCRxvGBawGwyTfoZF1UpzocGqvtjdx7J",
        signer: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
        type: "ED25519",
        sig: "zpoYmYqYv3p6533s2cHorZvjUUS6RGR3YfxpuJHZMzDrAeXCoT3NXEdjS9DYhns2vgRgAs1A4WPcqozEbcL7wwJX",
      },
      {
        created: "2022-02-14T10:03:35.589Z",
        name: "@ocap/qldb-chain-manager",
        pk: "z75CxPgkoiANhn1iCMRHQX2w6fSQPgi2qZiqbhQuy9Xo3",
        sig: "zVgg8CW2QbJnRdwrspqvxcUArnjp6VoxgEDSs76YURRnucLUMWCxKEwoV47TPinQX2UqdAAo8NkTb76V9wNke8by",
        signer: "z1Rq9qSoqvAq1NcJJTzKB1AnM991Cm4JrzW",
        type: "ED25519",
      },
    ],
    specVersion: "1.2.1",
    timeout: { start: 60 },
    title: "QLDB Chain Manager",
    version: "1.14.13",
    stats: { downloads: 162 },
    category: {
      name: "blockchain",
      locales: { zh: "区块链", en: "Blockchain" },
      _id: "ehbHn3Ceu9UQHRtQ",
      createdAt: "2022-01-11T01:49:44.009Z",
      updatedAt: "2022-01-11T01:49:44.009Z",
    },
    owner: {
      did: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
      name: "arcblock",
      role: "admin",
    },
    lastPublishedAt: "2022-02-15T01:54:00.877Z",
  },
  {
    author: {
      email: "wangshijun2010@gmail.com",
      name: "wangshijun",
      url: "http://github.com/wangshijun",
    },
    capabilities: { clusterMode: true, component: true },
    children: [],
    community: "",
    description:
      "Blockchain api built upon OCAP SDK that uses QLDB and elasticsearch as storage",
    did: "z8iZuohP9o6jfKeHgZK1gxke6usvrgK8Vw7B6",
    dist: {
      integrity:
        "sha512-oc/0+EdWyGiQlKPvZj2hW3lUVG1kg387RrRyoz3Y6/oRAJnOBCnQWzXI6oy54uKM8njOKLsCnjzbOmHkivhjRw==",
      tarball: "@ocapqldb-chain-api-1.14.13.tgz",
    },
    documentation: "",
    environments: [
      {
        default: "",
        description: "Please provide AWS QLDB access key",
        name: "AWS_ACCESS_KEY_ID",
        required: true,
        secure: false,
      },
      {
        default: "",
        description: "Please provide AWS QLDB access secret",
        name: "AWS_ACCESS_KEY_SECRET",
        required: true,
        secure: true,
      },
      {
        default: "",
        description: "Please provide AWS QLDB ledger region",
        name: "AWS_QLDB_REGION",
        required: true,
        secure: false,
      },
      {
        default: "",
        description: "Please provide AWS QLDB ledger name",
        name: "AWS_QLDB_LEDGER",
        required: true,
        secure: false,
      },
      {
        default: "",
        description: "Please provide elastic search endpoint",
        name: "ELASTIC_SEARCH_ENDPOINT",
        required: true,
        secure: true,
      },
      {
        default: "",
        description:
          "Please provide elastic search username for authentication",
        name: "ELASTIC_SEARCH_USERNAME",
        required: false,
        secure: true,
      },
      {
        default: "",
        description:
          "Please provide elastic search password for authentication",
        name: "ELASTIC_SEARCH_PASSWORD",
        required: false,
        secure: true,
      },
      {
        default: "",
        description: "Please provide elastic search table prefix",
        name: "ELASTIC_SEARCH_INDEX_PREFIX",
        required: false,
        secure: false,
      },
      {
        default: "test-chain",
        description: "Please provide id of the chain",
        name: "CHAIN_ID",
        required: true,
        secure: false,
      },
      {
        default: "TestChainToken",
        description: "Please provide name of the chain token",
        name: "CHAIN_TOKEN_NAME",
        required: false,
        secure: false,
      },
      {
        default: "18",
        description: "Please provide decimal of then chain token",
        name: "CHAIN_TOKEN_DECIMAL",
        required: false,
        secure: false,
      },
      {
        default: "MYT",
        description: "Please provide symbol of the chain token",
        name: "CHAIN_TOKEN_SYMBOL",
        required: false,
        secure: false,
      },
      {
        default: "1000000000",
        description: "Please provide supply of the chain token",
        name: "CHAIN_TOKEN_SUPPLY",
        required: false,
        secure: false,
      },
      {
        default: "",
        description: "Please provide preferred address of chain token",
        name: "CHAIN_TOKEN_ADDRESS",
        required: false,
        secure: false,
      },
      {
        default: "",
        description:
          "Please provide contract address of the foreign chain token",
        name: "CHAIN_TOKEN_FOREIGN_CONTRACT_ADDRESS",
        required: false,
        secure: false,
      },
      {
        default: "eth",
        description: "Please provide type of the foreign chain",
        name: "CHAIN_TOKEN_FOREIGN_CHAIN_TYPE",
        required: false,
        secure: false,
      },
      {
        default: "rinkeby",
        description: "Please provide name of the foreign chain",
        name: "CHAIN_TOKEN_FOREIGN_CHAIN_NAME",
        required: false,
        secure: false,
      },
      {
        default: "4",
        description: "Please provide id of the foreign chain",
        name: "CHAIN_TOKEN_FOREIGN_CHAIN_ID",
        required: false,
        secure: false,
      },
    ],
    files: ["blocklet.md", "screenshots/"],
    gitHash: "1d2c6b7d5339ed8b4cd8382812ab943a5770f7d0",
    group: "dapp",
    homepage: "",
    interfaces: [
      {
        name: "publicUrl",
        path: "/",
        port: "BLOCKLET_PORT",
        prefix: "*",
        protocol: "http",
        type: "web",
      },
    ],
    keywords: [],
    license: "",
    main: "blocklet.zip",
    name: "@ocap/qldb-chain-api",
    nftFactory: "",
    path: "/dapp/@ocap/qldb-chain-api",
    payment: { price: [], share: [] },
    requirements: { abtnode: ">=1.1.0", cpu: "*", os: "*" },
    screenshots: [
      "0-home.png",
      "1-txs.png",
      "2-account.png",
      "3-asset.png",
      "4-bridge.png",
      "5-bridge-move.png",
      "6-transfer.png",
    ],
    signatures: [
      {
        type: "ED25519",
        name: "Blocklet Store",
        signer: "zNKXtdqz6Jbw5mKpojK2nP5gRNiEGJY3mNFF",
        pk: "z8VahoQa6oS63Ym3rfsmzZEt9Moonbg4JSUiit5J7DRAV",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-02-15T01:54:10.907Z",
        sig: "z2sRNocMugKsfqLUUM7LpPeBnrTw9VNxCdzjRZxXagsoQKgTMaxv3pbDgr58Lt2XkNYDUcag3yqxZtjxj5Wk66Fya",
      },
      {
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-02-15T01:54:09.000Z",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        name: "@ocap/qldb-chain-api",
        pk: "z2eCsEyycLQPvqCRxvGBawGwyTfoZF1UpzocGqvtjdx7J",
        signer: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
        type: "ED25519",
        sig: "z2XhZh45EDkM87YN374M2QNf1QLTuUJGPCXSWGdp1aLkmhRj8oBb4GtBnQygbRvo4UKdk4Rqie14ACyE6dHAVQNYL",
      },
      {
        created: "2022-02-14T10:03:27.626Z",
        name: "@ocap/qldb-chain-api",
        pk: "z75CxPgkoiANhn1iCMRHQX2w6fSQPgi2qZiqbhQuy9Xo3",
        sig: "z2bByVLxtHahXKdfy4D895FRT3Ac2XsaCmK54YJMdjbhXro8D6gk2hD7kACtpDW3DoespGLRxQJB6BXS6VxAzo4eX",
        signer: "z1Rq9qSoqvAq1NcJJTzKB1AnM991Cm4JrzW",
        type: "ED25519",
      },
    ],
    specVersion: "1.2.1",
    timeout: { start: 60 },
    title: "QLDB Chain API",
    version: "1.14.13",
    stats: { downloads: 430 },
    category: {
      name: "blockchain",
      locales: { zh: "区块链", en: "Blockchain" },
      _id: "ehbHn3Ceu9UQHRtQ",
      createdAt: "2022-01-11T01:49:44.009Z",
      updatedAt: "2022-01-11T01:49:44.009Z",
    },
    owner: {
      did: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
      name: "arcblock",
      role: "admin",
    },
    lastPublishedAt: "2022-02-15T01:54:10.925Z",
  },
  {
    author: {
      email: "wangshijun2010@gmail.com",
      name: "wangshijun",
      url: "http://github.com/wangshijun",
    },
    capabilities: { clusterMode: false, component: true },
    children: [
      {
        mountPoints: [
          {
            child: { interfaceName: "publicUrl" },
            root: { interfaceName: "publicUrl", prefix: "/api" },
          },
        ],
        name: "@ocap/fs-chain-api",
        resolved:
          "https://registry.arcblock.io/api/blocklets/z8iZzecBVDH2M8kW5hrQ4wRubVksjtjNxH63z/blocklet.json",
      },
      {
        mountPoints: [
          {
            child: { interfaceName: "publicUrl" },
            root: { interfaceName: "publicUrl", prefix: "/" },
          },
        ],
        name: "@arcblock/block-explorer",
        resolved:
          "https://registry.arcblock.io/api/blocklets/z8iZyVVn6XsvcuiYhtdw3GoasMbtqR9BjvJz3/blocklet.json",
      },
    ],
    community: "",
    description:
      "Blockchain manager blocklet that combines FS chain API and block explorer blocklet",
    did: "z8ia2KGe3icfgRcVc9C1qCbWTBbpP2TrfPu7T",
    dist: {
      integrity:
        "sha512-5+7/YUwphXVxRxrZX8nP3XYk8jP4oxS7BaRLnhiP/LMn3APW8OQDDgiArlPJEykTfcN4XdwcpQCuJi0YML9cZg==",
      tarball: "@ocapfs-chain-manager-1.14.13.tgz",
    },
    documentation: "",
    environments: [
      {
        default: "/api",
        description: "Default chain endpoint of explorer",
        name: "EXPLORER_CHAIN_ENDPOINT",
        required: false,
        secure: false,
      },
    ],
    files: ["blocklet.md", "screenshots/"],
    gitHash: "1d2c6b7d5339ed8b4cd8382812ab943a5770f7d0",
    group: "gateway",
    homepage: "",
    interfaces: [
      {
        name: "publicUrl",
        path: "/",
        port: "BLOCKLET_PORT",
        prefix: "*",
        protocol: "http",
        type: "web",
      },
    ],
    license: "",
    name: "@ocap/fs-chain-manager",
    nftFactory: "",
    path: "/gateway/@ocap/fs-chain-manager",
    payment: { price: [], share: [] },
    requirements: { abtnode: ">=1.2.5", cpu: "*", os: "*" },
    screenshots: [
      "0-home.png",
      "1-txs.png",
      "2-account.png",
      "3-asset.png",
      "4-bridge.png",
      "5-bridge-move.png",
      "6-transfer.png",
    ],
    signatures: [
      {
        type: "ED25519",
        name: "Blocklet Store",
        signer: "zNKXtdqz6Jbw5mKpojK2nP5gRNiEGJY3mNFF",
        pk: "z8VahoQa6oS63Ym3rfsmzZEt9Moonbg4JSUiit5J7DRAV",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-02-15T01:54:22.544Z",
        sig: "z4JpD5iAqDidtZ7VEigZquNzVBWFwduJa7vLNzjJi3qHqw3Ao5Ln4SW7SmBzVRd3z5Bn3xe1sZTd1hiuCNJzRXt6b",
      },
      {
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-02-15T01:54:18.503Z",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        name: "@ocap/fs-chain-manager",
        pk: "z2eCsEyycLQPvqCRxvGBawGwyTfoZF1UpzocGqvtjdx7J",
        signer: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
        type: "ED25519",
        sig: "z2W5iuMu66GgHJ9u2GanRLxa58oyf1J2muu2DuGTWTH3tmckkAdHMasJbEhn9n3dCRjAm7JVGJZHuGqGLL9k4cBoq",
      },
      {
        created: "2022-02-14T10:03:09.509Z",
        name: "@ocap/fs-chain-manager",
        pk: "z75CxPgkoiANhn1iCMRHQX2w6fSQPgi2qZiqbhQuy9Xo3",
        sig: "zbPjRRq11QxU5P3gJJKiDHr5HAJtynTxxd4gPDJVoYF2CZ7to49EJBWHp22mrm9en8AbBrAw3tqbuXgKZVvcJ38v",
        signer: "z1Rq9qSoqvAq1NcJJTzKB1AnM991Cm4JrzW",
        type: "ED25519",
      },
    ],
    specVersion: "1.2.1",
    timeout: { start: 60 },
    title: "FS Chain Manager",
    version: "1.14.13",
    stats: { downloads: 182 },
    category: {
      name: "developer-tools",
      locales: { en: "Developer Tools", zh: "开发者工具" },
      _id: "UXLwYKl1wa1qAhVe",
      createdAt: "2022-01-11T01:48:16.351Z",
      updatedAt: "2022-01-11T01:48:45.576Z",
    },
    owner: {
      did: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
      name: "arcblock",
      role: "admin",
    },
    lastPublishedAt: "2022-02-15T01:54:22.559Z",
  },
  {
    author: { email: "blocklet@arcblock.io", name: "Arcblock" },
    capabilities: { clusterMode: false, component: false },
    children: [
      {
        mountPoints: [
          {
            child: { interfaceName: "publicUrl" },
            root: { interfaceName: "publicUrl", prefix: "/store" },
          },
        ],
        name: "nft-store",
        resolved:
          "https://store.blocklet.dev/api/blocklets/z8iZqkCjLP6TZpR12tT3jESWxB8SGzNsx8nZa/blocklet.json",
      },
    ],
    community: "https://community.arcblockio.cn",
    description:
      "Serve blocklet store and an embed NFT store for user to purchase blocklets.",
    did: "z8ia29UsENBg6tLZUKi2HABj38Cw1LmHZocbQ",
    dist: {
      integrity:
        "sha512-300DV0IZsDgZH0LBLBFl/frR7bakPGNCKbQf1XnvupjDNYNfDA6QkONt4Es80v+qP9KsuFDqqYAGlU4msdAWnA==",
      tarball: "blocklet-registry-service-0.5.10.tgz",
    },
    documentation: "https://docs.arcblock.io",
    environments: [
      {
        default: "",
        description: "Please provide a logo for the store",
        name: "STORE_LOGO",
        required: false,
        secure: false,
      },
      {
        default: "",
        description: "Please provide a maintainer did for the store",
        name: "STORE_MAINTAINER",
        required: true,
        secure: false,
      },
      {
        default: "0.3",
        description:
          "Minimum requirement of blocklet payment share to accept publish",
        name: "SHARE_REQUIREMENT",
        required: false,
        secure: false,
      },
      {
        default: "https://beta.abtnetwork.io/api/",
        description:
          "Please provide endpoint of the chain where NFT factory are stored",
        name: "CHAIN_HOST",
        required: true,
        secure: false,
      },
      {
        default: "",
        description:
          "URL used to boost user experience when downloading blocklets",
        name: "CDN_URL",
        required: false,
        secure: false,
      },
      {
        default: "https://install.arcblock.io/launch/",
        description: "Address to launch blocklet",
        name: "LAUNCH_URL",
        required: false,
        secure: false,
      },
    ],
    files: [
      "screenshots",
      "public",
      "api/hooks/*.js",
      "migration/*.js",
      "logo.svg",
      "blocklet.md",
      "README.md",
      "build",
    ],
    gitHash: "5583409bd38b0f8954b108d951cdc3fb18550416",
    group: "dapp",
    homepage: "https://github.com/blocklet/blocklet-store",
    interfaces: [
      {
        endpoints: [
          {
            meta: {
              params: [
                {
                  description: "Blocklet purchase credential factory address",
                  name: "factory",
                },
              ],
              payable: true,
              vcType: "BlockletPurchaseCredential",
            },
            path: "/store/api/did/acquire-asset/token",
            type: "IssueVc",
          },
        ],
        name: "publicUrl",
        path: "/",
        port: "BLOCKLET_PORT",
        prefix: "*",
        protocol: "http",
        services: [
          {
            config: { blockUnauthenticated: false },
            name: "@abtnode/auth-service",
          },
        ],
        type: "web",
      },
    ],
    keywords: ["blocklet", "registry", "store"],
    license: "Apache-2.0",
    logo: "logo.svg",
    main: "blocklet.zip",
    name: "blocklet-registry-service",
    nftFactory: "",
    path: "/dapp/blocklet-registry-service",
    payment: { price: [], share: [] },
    repository: {
      type: "git",
      url: "git+https://github.com/blocklet/blocklet-store.git",
    },
    requirements: { abtnode: ">=1.2.6", cpu: "*", os: "*" },
    screenshots: [
      "0-home.png",
      "1-detail.png",
      "2-detail-versions.png",
      "3-detail-download.png",
    ],
    scripts: { dev: "npm run start", preStart: "node api/hooks/pre-start.js" },
    signatures: [
      {
        type: "ED25519",
        name: "Blocklet Store",
        signer: "zNKXtdqz6Jbw5mKpojK2nP5gRNiEGJY3mNFF",
        pk: "z8VahoQa6oS63Ym3rfsmzZEt9Moonbg4JSUiit5J7DRAV",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-02-18T03:52:40.060Z",
        sig: "z469u7M8LczJnnPsVHuKmQH2NAC9BSGevRv22irDqCEfHsQhZMbnxWmHWJ9nicjkzHfYZzbjRV3QEbnDuxuezPDy5",
      },
      {
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-02-18T03:52:38.613Z",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        name: "blocklet-registry-service",
        pk: "z2eCsEyycLQPvqCRxvGBawGwyTfoZF1UpzocGqvtjdx7J",
        signer: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
        type: "ED25519",
        sig: "z4VK5cnaJ8zLN1UmAgSCEunkqYV7sPhfVNiFxFNMBzskG9e3zi8hNnz6bVGNfHmecyXbTvb6H2vM95P3gM3p88HFx",
      },
      {
        created: "2022-02-18T03:47:10.636Z",
        name: "blocklet-registry-service",
        pk: "z75CxPgkoiANhn1iCMRHQX2w6fSQPgi2qZiqbhQuy9Xo3",
        sig: "z3WtpVB8W2S6iQ9rD7gsmFJUDN6ZofRxVP7bAwKwY2u6ek97jmhJf3eh7bU5JsW6YjM33mu626hWS9eu6xdCiptxQ",
        signer: "z1Rq9qSoqvAq1NcJJTzKB1AnM991Cm4JrzW",
        type: "ED25519",
      },
    ],
    specVersion: "1.2.2",
    support: "support@arcblock.io",
    timeout: { start: 60 },
    title: "Blocklet Store",
    version: "0.5.10",
    stats: { downloads: 151 },
    category: {
      name: "dao",
      locales: { zh: "DAO", en: "DAO" },
      _id: "aQFpIUzL2vshltnY",
      createdAt: "2022-01-11T01:52:00.394Z",
      updatedAt: "2022-01-11T01:52:00.394Z",
    },
    owner: {
      did: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
      name: "arcblock",
      role: "admin",
    },
    lastPublishedAt: "2022-02-18T03:52:40.073Z",
  },
  {
    author: {
      email: "wangshijun2010@gmail.com",
      name: "wangshijun",
      url: "http://github.com/wangshijun",
    },
    capabilities: { clusterMode: false, component: true },
    children: [],
    community: "",
    description:
      "Blockchain api built upon OCAP SDK that persists data on the disk",
    did: "z8iZzecBVDH2M8kW5hrQ4wRubVksjtjNxH63z",
    dist: {
      integrity:
        "sha512-rCPzPmMMpVeaIbV4vAuHMD/KLw649GQMFRYMMxUwfwfHpwIcbJQ49XOUr4VDdR9dQf/rMpJKluZ9wJFkP2OeQg==",
      tarball: "@ocapfs-chain-api-1.14.13.tgz",
    },
    documentation: "",
    environments: [
      {
        default: "test-chain",
        description: "Please provide id of the chain",
        name: "CHAIN_ID",
        required: true,
        secure: false,
      },
      {
        default: "TestChainToken",
        description: "Please provide name of the chain token",
        name: "CHAIN_TOKEN_NAME",
        required: false,
        secure: false,
      },
      {
        default: "18",
        description: "Please provide decimal of then chain token",
        name: "CHAIN_TOKEN_DECIMAL",
        required: false,
        secure: false,
      },
      {
        default: "MYT",
        description: "Please provide symbol of the chain token",
        name: "CHAIN_TOKEN_SYMBOL",
        required: false,
        secure: false,
      },
      {
        default: "1000000000",
        description: "Please provide supply of the chain token",
        name: "CHAIN_TOKEN_SUPPLY",
        required: false,
        secure: false,
      },
      {
        default: "",
        description: "Please provide preferred address of chain token",
        name: "CHAIN_TOKEN_ADDRESS",
        required: false,
        secure: false,
      },
      {
        default: "",
        description:
          "Please provide contract address of the foreign chain token",
        name: "CHAIN_TOKEN_FOREIGN_CONTRACT_ADDRESS",
        required: false,
        secure: false,
      },
      {
        default: "eth",
        description: "Please provide type of the foreign chain",
        name: "CHAIN_TOKEN_FOREIGN_CHAIN_TYPE",
        required: false,
        secure: false,
      },
      {
        default: "rinkeby",
        description: "Please provide name of the foreign chain",
        name: "CHAIN_TOKEN_FOREIGN_CHAIN_NAME",
        required: false,
        secure: false,
      },
      {
        default: "4",
        description: "Please provide id of the foreign chain",
        name: "CHAIN_TOKEN_FOREIGN_CHAIN_ID",
        required: false,
        secure: false,
      },
    ],
    files: ["blocklet.md", "screenshots/"],
    gitHash: "1d2c6b7d5339ed8b4cd8382812ab943a5770f7d0",
    group: "dapp",
    homepage: "",
    interfaces: [
      {
        name: "publicUrl",
        path: "/",
        port: "BLOCKLET_PORT",
        prefix: "*",
        protocol: "http",
        type: "web",
      },
    ],
    keywords: [],
    license: "",
    main: "blocklet.zip",
    name: "@ocap/fs-chain-api",
    nftFactory: "",
    path: "/dapp/@ocap/fs-chain-api",
    payment: { price: [], share: [] },
    requirements: { abtnode: ">=1.1.0", cpu: "*", os: "*" },
    screenshots: [
      "0-home.png",
      "1-txs.png",
      "2-account.png",
      "3-asset.png",
      "4-bridge.png",
      "5-bridge-move.png",
      "6-transfer.png",
    ],
    signatures: [
      {
        type: "ED25519",
        name: "Blocklet Store",
        signer: "zNKXtdqz6Jbw5mKpojK2nP5gRNiEGJY3mNFF",
        pk: "z8VahoQa6oS63Ym3rfsmzZEt9Moonbg4JSUiit5J7DRAV",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-02-15T01:54:37.069Z",
        sig: "z8zzgRBikr3qpYL11Nw6WHmLgUbZdWN4K2wSTwVWmmTPVEhTKeCBcPaQqczcrQKiNMr5tz6TUas3zuvXjq3aHrQc",
      },
      {
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-02-15T01:54:30.803Z",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        name: "@ocap/fs-chain-api",
        pk: "z2eCsEyycLQPvqCRxvGBawGwyTfoZF1UpzocGqvtjdx7J",
        signer: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
        type: "ED25519",
        sig: "zyY54HcXyqSWPWECHgS6WqRbxLetbJZLxkStQMhwP4F8RGi9zGjs5FzJaM3qJ1S5v8ax8cahSqcwKBFtX7NteGs1",
      },
      {
        created: "2022-02-14T10:03:00.657Z",
        name: "@ocap/fs-chain-api",
        pk: "z75CxPgkoiANhn1iCMRHQX2w6fSQPgi2qZiqbhQuy9Xo3",
        sig: "z2pnPNv22Jc6nCPckpuGj6bG52frpf29s7U1L4cLBNcd8NaJDFb86P9VcBXyRqWwTbjDAMEn5HWA64FiZeimm3R73",
        signer: "z1Rq9qSoqvAq1NcJJTzKB1AnM991Cm4JrzW",
        type: "ED25519",
      },
    ],
    specVersion: "1.2.1",
    timeout: { start: 60 },
    title: "File Chain API",
    version: "1.14.13",
    stats: { downloads: 607 },
    category: {
      name: "developer-tools",
      locales: { en: "Developer Tools", zh: "开发者工具" },
      _id: "UXLwYKl1wa1qAhVe",
      createdAt: "2022-01-11T01:48:16.351Z",
      updatedAt: "2022-01-11T01:48:45.576Z",
    },
    owner: {
      did: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
      name: "arcblock",
      role: "admin",
    },
    lastPublishedAt: "2022-02-15T01:54:37.077Z",
  },
  {
    author: { email: "shijun@arcblock.io", name: "wangshijun" },
    capabilities: { clusterMode: false },
    children: [],
    community: "",
    description: "Verify once and use everywhere.",
    did: "z8iZtvDiFYckxQ6rECTD2bL1p35WGyTDyq1W8",
    dist: {
      integrity:
        "sha512-9JWI6aHm/8HkC8hWTekw44i3IzAnwbzADUK96pO1iqUi/5rK0QyLrKK/1/RjfREfY4t43J7oiTPkz6h+sBTVSg==",
      tarball: "@arcblockdid-kyc-0.20.6.tgz",
    },
    documentation: "",
    environments: [
      {
        default: "",
        description: "Please provide a mailgun smtp user name to start",
        name: "MAILGUN_SMTP_USER",
        required: true,
        secure: true,
      },
      {
        default: "",
        description: "Please provide a mailgun smtp password to start",
        name: "MAILGUN_SMTP_PASSWORD",
        required: true,
        secure: true,
      },
      {
        default: "beta",
        description: "Please provide id of local chain id",
        name: "APP_CHAIN_ID",
        required: true,
        secure: false,
      },
      {
        default: "https://beta.abtnetwork.io/api/",
        description: "Please provide endpoint of local chain host",
        name: "APP_CHAIN_HOST",
        required: true,
        secure: false,
      },
    ],
    files: ["api/libs/hooks/pre-start.js"],
    gitHash: "295c3eac8856ea48834ccb0e684c517acd76e9d9",
    group: "dapp",
    homepage: "",
    interfaces: [
      {
        name: "publicUrl",
        path: "/",
        port: "BLOCKLET_PORT",
        prefix: "*",
        protocol: "tcp",
        services: [
          {
            config: {
              ignoreUrls: [
                "/api/did/**",
                "/api/agent/**",
                "/api/nft/**",
                "/blocklet/**",
                "/instance/**",
              ],
            },
            name: "@abtnode/auth-service",
          },
        ],
        type: "web",
      },
    ],
    keywords: ["arcblock", "forge", "starter", "react", "javascript"],
    license: "Apache-2.0",
    logo: "logo.png",
    main: "blocklet.zip",
    name: "@arcblock/did-kyc",
    nftFactory: "",
    path: "/dapp/@arcblock/did-kyc",
    payment: { price: [], share: [] },
    repository: {
      type: "git",
      url: "git+https://github.com/ArcBlock/forge-dapp-starters.git#master",
    },
    requirements: { abtnode: ">=1.1.17" },
    screenshots: [],
    scripts: {
      dev: "npm run start",
      preDeploy: "npm run bundle",
      preStart: "node api/libs/hooks/pre-start.js",
    },
    signatures: [
      {
        type: "ED25519",
        name: "Blocklet Store",
        signer: "zNKXtdqz6Jbw5mKpojK2nP5gRNiEGJY3mNFF",
        pk: "z8VahoQa6oS63Ym3rfsmzZEt9Moonbg4JSUiit5J7DRAV",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2021-12-08T12:56:16.145Z",
        sig: "z33tYk9Mh8GgHAoWTEWjaUKwzNVvMDJZDkN9ZGhwZ1JRTQdnaAtoiP3Qqw38SgJUCUUTXfAgd2t6YJvNzeVFygaaD",
      },
      {
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2021-12-08T12:56:14.412Z",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        name: "@arcblock/did-kyc",
        pk: "z2eCsEyycLQPvqCRxvGBawGwyTfoZF1UpzocGqvtjdx7J",
        signer: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
        type: "ED25519",
        sig: "z3Vdm7gTMaotX865KZD3vNepEQJJ4SGYJ4JXkatJtFw9mmCXjL8EWYPzJrYTUPke5sza2cdVPmk5SQ3xR13c8bfaU",
      },
      {
        created: "2021-12-07T11:02:58.903Z",
        name: "@arcblock/did-kyc",
        pk: "z75CxPgkoiANhn1iCMRHQX2w6fSQPgi2qZiqbhQuy9Xo3",
        sig: "z2vjPsGNhhn9noQDGWxKUVK3MTodG8xpi53KjwsM7nnAprcPcKVrYzrCypYNCFjTaJv2vaFcwhGnkPvnmWFCYjhEP",
        signer: "z1Rq9qSoqvAq1NcJJTzKB1AnM991Cm4JrzW",
        type: "ED25519",
      },
    ],
    specVersion: "1.2.0",
    timeout: { start: 10 },
    title: "DID KYC",
    version: "0.20.6",
    stats: { downloads: 205 },
    category: {
      name: "dao",
      locales: { zh: "DAO", en: "DAO" },
      _id: "aQFpIUzL2vshltnY",
      createdAt: "2022-01-11T01:52:00.394Z",
      updatedAt: "2022-01-11T01:52:00.394Z",
    },
    owner: {
      did: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
      name: "arcblock",
      role: "admin",
    },
    lastPublishedAt: "2021-12-07T11:03:02.037Z",
  },
  {
    author: {
      email: "shijun@arcblock.io",
      name: "wangshijun",
      url: "http://github.com/wangshijun",
    },
    capabilities: { clusterMode: false },
    children: [],
    community: "https://gitter.im/ArcBlock/community",
    description:
      "a static dapp that supports connecting to any forge powered blockchain",
    did: "z8iZyVVn6XsvcuiYhtdw3GoasMbtqR9BjvJz3",
    dist: {
      integrity:
        "sha512-nRYch6sd48njwHhD0slGp+C25+DJLUjJcZyjltsy52ezFqIu6+NX48Kc80G/eaZOUXom7Ihi3C5i9nWrbkapUA==",
      tarball: "@arcblockblock-explorer-2.3.46.tgz",
    },
    documentation: "https://docs.arcblock.io",
    environments: [
      {
        default: "",
        description: "Default chain endpoint of explorer",
        name: "EXPLORER_CHAIN_ENDPOINT",
        required: false,
        secure: false,
      },
    ],
    files: [
      "static/",
      "screenshots/",
      "logo.png",
      "blocklet.js",
      "blocklet.md",
      "README.md",
    ],
    gitHash: "5f9898d605dc5d2654c14299f2afe159a3b1e685",
    group: "static",
    homepage: "",
    interfaces: [
      {
        name: "publicUrl",
        path: "/",
        port: "BLOCKLET_PORT",
        prefix: "*",
        protocol: "tcp",
        type: "web",
      },
    ],
    keywords: ["blockchain", "forge", "developer", "explorer"],
    license: "Apache-2.0",
    logo: "logo.png",
    main: "static",
    name: "@arcblock/block-explorer",
    nftFactory: "",
    path: "/static/@arcblock/block-explorer",
    payment: { price: [], share: [] },
    repository: {
      type: "git",
      url: "git+https://github.com/ArcBlock/block-explorer.git",
    },
    requirements: { abtnode: ">=1.2.5" },
    screenshots: [
      "0-home.png",
      "1-txs.png",
      "2-account.png",
      "3-asset.png",
      "4-bridge.png",
      "5-bridge-move.png",
      "6-transfer.png",
    ],
    scripts: {},
    signatures: [
      {
        type: "ED25519",
        name: "Blocklet Store",
        signer: "zNKXtdqz6Jbw5mKpojK2nP5gRNiEGJY3mNFF",
        pk: "z8VahoQa6oS63Ym3rfsmzZEt9Moonbg4JSUiit5J7DRAV",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-02-14T01:02:06.444Z",
        sig: "z29rxbDdWmBDqxDtjKGdmbXaXhWYvpigfrfGmDXBshpfvVMeCoA9EeqgzonLKzfArVBUZRhDEUoqaDFEdC5BrvCQt",
      },
      {
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-02-14T01:02:04.368Z",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        name: "@arcblock/block-explorer",
        pk: "z2eCsEyycLQPvqCRxvGBawGwyTfoZF1UpzocGqvtjdx7J",
        signer: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
        type: "ED25519",
        sig: "z42pBTuw9U4ddLq4bPKPkjT3y8xwDj76uScdeRqKzj7G85S8ewShXQRAsK9mfnRbVj6tnzFKSFpQDdmbNHDb47YB8",
      },
      {
        created: "2022-02-11T08:02:38.368Z",
        name: "@arcblock/block-explorer",
        pk: "z75CxPgkoiANhn1iCMRHQX2w6fSQPgi2qZiqbhQuy9Xo3",
        sig: "z4cD1aP6EWGcz8A7PPfGsxiLZT9gfPTxkwhdcoh45wKJ2FhsCemJj5vKrJgVt19TRgZEeGh68bNWfPHLzrhrNsETB",
        signer: "z1Rq9qSoqvAq1NcJJTzKB1AnM991Cm4JrzW",
        type: "ED25519",
      },
    ],
    specVersion: "1.2.1",
    support: "support@arcblock.io",
    timeout: { start: 60 },
    title: "Blockchain Explorer",
    version: "2.3.46",
    stats: { downloads: 5311 },
    category: {
      name: "blockchain",
      locales: { zh: "区块链", en: "Blockchain" },
      _id: "ehbHn3Ceu9UQHRtQ",
      createdAt: "2022-01-11T01:49:44.009Z",
      updatedAt: "2022-01-11T01:49:44.009Z",
    },
    owner: {
      did: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
      name: "arcblock",
      role: "admin",
    },
    lastPublishedAt: "2022-02-14T01:02:06.451Z",
  },
  {
    author: {
      email: "wangshijun2010@gmail.com",
      name: "wangshijun",
      url: "http://github.com/wangshijun",
    },
    capabilities: { clusterMode: false },
    children: [],
    community: "",
    description:
      "Demo blocklet that shows how to serve a static html5 game with Blocklet Server",
    did: "z8ia4e5vAeDsQEE2P26bQqz9oWR1Lxg9qUMaV",
    dist: {
      integrity:
        "sha512-5FE5O6XaPNsGT67kZ0KPaYUOSZ2QrUALzJg3LfUxHgk/IgQX8c+8gccXGCi53sY7AWlOaqP/7DO8FAEZZ4+xnw==",
      tarball: "static-demo-blocklet-1.1.21.tgz",
    },
    documentation: "",
    environments: [],
    files: [
      "app/",
      "screenshots/",
      "logo.png",
      "blocklet.yml",
      "blocklet.md",
      "README.md",
    ],
    gitHash: "aefe37a5c7fa4fb24b2f23c5799af7bc9166a2b3",
    group: "static",
    homepage: "",
    interfaces: [
      {
        name: "publicUrl",
        path: "/",
        port: "BLOCKLET_PORT",
        prefix: "*",
        protocol: "tcp",
        type: "web",
      },
    ],
    keywords: ["demo", "game", "blocklet"],
    license: "MIT",
    logo: "logo.png",
    main: "app",
    name: "static-demo-blocklet",
    nftFactory: "",
    path: "/static/static-demo-blocklet",
    payment: { price: [], share: [] },
    repository: {
      type: "git",
      url: "git+https://github.com/blocklet/html-2048-sample.git",
    },
    requirements: { abtnode: ">=1.1.0", cpu: "*", os: "*" },
    screenshots: ["0-home.png"],
    signatures: [
      {
        type: "ED25519",
        name: "Blocklet Store",
        signer: "zNKXtdqz6Jbw5mKpojK2nP5gRNiEGJY3mNFF",
        pk: "z8VahoQa6oS63Ym3rfsmzZEt9Moonbg4JSUiit5J7DRAV",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-01-29T10:06:05.473Z",
        sig: "z4DTXBYUuUksUnHMk1p7EGYV22AZtk65UFoCKX8QfqBQTYBuHV6RELDPfVo1mWEP2PhyJUe8f5Fk9CPenrEQTCuKk",
      },
      {
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-01-29T10:06:03.272Z",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        name: "static-demo-blocklet",
        pk: "z2eCsEyycLQPvqCRxvGBawGwyTfoZF1UpzocGqvtjdx7J",
        signer: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
        type: "ED25519",
        sig: "z3JksViPMfzbNMiuVboMqXkmTrSeB1FL1smtYcVRan1QzbL7T9Ym3v9zcam5VCDYrjhQ4wFXwriYugKAEKA6DCgMt",
      },
      {
        created: "2022-01-29T10:02:18.346Z",
        name: "static-demo-blocklet",
        pk: "z75CxPgkoiANhn1iCMRHQX2w6fSQPgi2qZiqbhQuy9Xo3",
        sig: "z2zqYNnnhtP22pWb6FNw6JGqkVNPZiQ8eLpBNNSvsJXjc9rqGBF7mZVEBjRV6W51Bagh1yMxm1MZfJ8iFoZsadrAg",
        signer: "z1Rq9qSoqvAq1NcJJTzKB1AnM991Cm4JrzW",
        type: "ED25519",
      },
    ],
    specVersion: "1.2.1",
    timeout: { start: 10 },
    title: "Static Demo",
    version: "1.1.21",
    stats: { downloads: 19969 },
    category: {
      name: "fun",
      locales: { zh: "娱乐", en: "Fun" },
      _id: "6TYF6yIvrVvaNUkw",
      createdAt: "2022-01-11T01:48:16.351Z",
      updatedAt: "2022-01-11T01:48:16.351Z",
    },
    owner: {
      did: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
      name: "arcblock",
      role: "admin",
    },
    lastPublishedAt: "2022-01-29T10:06:05.483Z",
  },
  {
    author: {
      email: "wangshijun2010@gmail.com",
      name: "wangshijun",
      url: "http://github.com/wangshijun",
    },
    capabilities: { clusterMode: false },
    children: [],
    community: "https://gitter.im/ArcBlock/community",
    description:
      "Blocklet Server Documentation, a help documentation for quickly get started with Blocklet Server.",
    did: "z8ia5NLSuFwhPimBJHRdPmp6yx9fG8rcFex4b",
    dist: {
      integrity:
        "sha512-sJeg19n70VpHmssz8f2zz3ccMPUYW9TxbvF9IAQY9wBKv4unfnwNf4otn0uAcRzpYXzQUlYR8Iecvrbhc+22Gg==",
      tarball: "@arcblockabtnode-docs-0.5.5.tgz",
    },
    documentation: "https://docs.arcblock.io",
    environments: [],
    files: ["public/", "screenshots/", "blocklet.md"],
    gitHash: "69c5580cf779dca22173586eb23e81da9d24fc81",
    group: "static",
    homepage: "https://github.com/ArcBlock/abtnode-docs-power-user#readme",
    interfaces: [
      {
        name: "publicUrl",
        path: "/",
        port: "BLOCKLET_PORT",
        prefix: "/abtnode",
        protocol: "tcp",
        type: "web",
      },
    ],
    keywords: ["Docs", "ABTNode"],
    license: "MIT",
    main: "public",
    name: "@arcblock/abtnode-docs",
    nftFactory: "",
    path: "/static/@arcblock/abtnode-docs",
    payment: { price: [], share: [] },
    repository: {
      type: "git",
      url: "git+https://github.com/ArcBlock/abtnode-docs.git",
    },
    requirements: { abtnode: ">=1.1.0", cpu: "*", os: "*" },
    screenshots: [
      "0-home.png",
      "1-platform.png",
      "2-developer.png",
      "3-use-cases.png",
      "4-learning.png",
    ],
    scripts: {},
    signatures: [
      {
        type: "ED25519",
        name: "Blocklet Store",
        signer: "zNKXtdqz6Jbw5mKpojK2nP5gRNiEGJY3mNFF",
        pk: "z8VahoQa6oS63Ym3rfsmzZEt9Moonbg4JSUiit5J7DRAV",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-01-30T00:11:24.041Z",
        sig: "z2xyguQUdW4S5V6BfTFdCHjjpdhYvuDH2qLWkZFJ5RBm94BKMuk4K23cdHn3eJ9T8ksWgNgVgnMFurEpYXcp7jHjy",
      },
      {
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-01-30T00:11:21.507Z",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        name: "@arcblock/abtnode-docs",
        pk: "z2eCsEyycLQPvqCRxvGBawGwyTfoZF1UpzocGqvtjdx7J",
        signer: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
        type: "ED25519",
        sig: "z2SK7ZAssfdkpraPXtytapqBsgsAzxrjHfGJ1Q7VyH6ndDuaZYqYhvUow6EmHTAwZ2LYWBiT2iaGUQmK39y15XEZ6",
      },
      {
        created: "2022-01-29T13:32:46.690Z",
        name: "@arcblock/abtnode-docs",
        pk: "z75CxPgkoiANhn1iCMRHQX2w6fSQPgi2qZiqbhQuy9Xo3",
        sig: "z45TNyQWYX3WMLHvAP7Q8NuWW1iR3rh6727pQvzEG3AUYhuwkySYpnZBnk3xmqPJ9SGbX25mBp6j2C2Tr4bQhHhmF",
        signer: "z1Rq9qSoqvAq1NcJJTzKB1AnM991Cm4JrzW",
        type: "ED25519",
      },
    ],
    specVersion: "1.2.1",
    support: "support@arcblock.io",
    timeout: { start: 10 },
    title: "Blocklet Server Docs",
    version: "0.5.5",
    stats: { downloads: 4250 },
    category: {
      name: "developer-tools",
      locales: { en: "Developer Tools", zh: "开发者工具" },
      _id: "UXLwYKl1wa1qAhVe",
      createdAt: "2022-01-11T01:48:16.351Z",
      updatedAt: "2022-01-11T01:48:45.576Z",
    },
    owner: {
      did: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
      name: "arcblock",
      role: "admin",
    },
    lastPublishedAt: "2022-01-30T00:11:24.050Z",
  },
  {
    author: {
      email: "shijun@arcblock.io",
      name: "wangshijun",
      url: "http://github.com/wangshijun",
    },
    capabilities: { clusterMode: false },
    children: [],
    community: "",
    description: "Start experiencing your digital world with ABT Wallet",
    did: "z8iZqWsTGg48WLuX7jmTnadbhJrMZuhfrNTcY",
    dist: {
      integrity:
        "sha512-ZETH9Kk3t3DbBS/4J/VIxgsAnKxriIUPVCwk1SW5/wpPCRTXHhsAyJ/39c0h/NjMbu1W5RaFBSBt2PoT8RZKww==",
      tarball: "@arcblockwww-wallet-2.5.12.tgz",
    },
    documentation: "",
    environments: [
      {
        default: "beta",
        description: "Please provide a valid chain id to start",
        name: "CHAIN_ID",
        required: true,
        secure: false,
      },
      {
        default: "https://beta.abtnetwork.io/api",
        description: "Please provide a valid chain host to start",
        name: "CHAIN_HOST",
        required: true,
        secure: false,
      },
    ],
    files: ["api/hooks/pre-start.js"],
    gitHash: "ac25ec0dc3b5bf96a9b3bd46ceba6e8320289e79",
    group: "dapp",
    homepage: "https://github.com/ArcBlock/www-wallet#readme",
    interfaces: [
      {
        name: "publicUrl",
        path: "/",
        port: "BLOCKLET_PORT",
        prefix: "/",
        protocol: "tcp",
        type: "web",
      },
    ],
    keywords: ["Dapp", "Demo", "Wallet"],
    license: "MIT",
    main: "blocklet.zip",
    name: "@arcblock/www-wallet",
    nftFactory: "",
    path: "/dapp/@arcblock/www-wallet",
    payment: { price: [], share: [] },
    repository: {
      type: "git",
      url: "git+https://github.com/ArcBlock/www-wallet.git",
    },
    requirements: { abtnode: ">=1.1.0", cpu: "*", os: "*" },
    screenshots: [],
    scripts: { preStart: "node api/hooks/pre-start.js" },
    signatures: [
      {
        type: "ED25519",
        name: "Blocklet Store",
        signer: "zNKXtdqz6Jbw5mKpojK2nP5gRNiEGJY3mNFF",
        pk: "z8VahoQa6oS63Ym3rfsmzZEt9Moonbg4JSUiit5J7DRAV",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-01-30T00:11:32.409Z",
        sig: "z4TfvtHoWJxzy1K6NZqnq3YvVXsZTbpvKKk517cWTMiu5obgtGNADuQkjRw2mcTveo2YAg3a7PE3bTAfBgirkWZgK",
      },
      {
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-01-30T00:11:30.175Z",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        name: "@arcblock/www-wallet",
        pk: "z2eCsEyycLQPvqCRxvGBawGwyTfoZF1UpzocGqvtjdx7J",
        signer: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
        type: "ED25519",
        sig: "z5usg1EHPUynKsBcKjaJKNhRrYYmtWsUAU6KrrJrZZcXc6od4A2MqNgSS3dDY3MLbSYW8txitDfHDrF7NeQVX6XLV",
      },
      {
        created: "2022-01-29T13:33:05.907Z",
        name: "@arcblock/www-wallet",
        pk: "z75CxPgkoiANhn1iCMRHQX2w6fSQPgi2qZiqbhQuy9Xo3",
        sig: "z5jATr3AQ243CFv6BqVUVRWfZySybX8wJ4FZRMParYVA76ocyGhW9sTaPWneLn9TkxGHoGqSZfrU438EbDY2w6yRm",
        signer: "z1Rq9qSoqvAq1NcJJTzKB1AnM991Cm4JrzW",
        type: "ED25519",
      },
    ],
    specVersion: "1.2.1",
    timeout: { start: 10 },
    title: "Wallet Demo",
    version: "2.5.12",
    stats: { downloads: 1928 },
    category: {
      name: "fun",
      locales: { zh: "娱乐", en: "Fun" },
      _id: "6TYF6yIvrVvaNUkw",
      createdAt: "2022-01-11T01:48:16.351Z",
      updatedAt: "2022-01-11T01:48:16.351Z",
    },
    owner: {
      did: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
      name: "arcblock",
      role: "admin",
    },
    lastPublishedAt: "2022-01-30T00:11:32.427Z",
  },
  {
    capabilities: { clusterMode: false },
    children: [],
    community: "",
    description: "A blocklet for uniswap blocklet",
    did: "z8iZsspkkY4AEXqRj8pAWKafC4KM3zN2WfNGA",
    dist: {
      integrity:
        "sha512-g+2mKXt6ME1E8CCAtQtqYVLq6j+dRXL6ZhrciXR8yJGBSrCVtNtNdO1xo4A6DX2jjh80YCwaMqaOZrbK3kI7kw==",
      tarball: "uniswap-blocklet-0.2.7.tgz",
    },
    documentation: "",
    environments: [],
    files: [
      "build",
      "screenshots",
      "logo.png",
      "blocklet.md",
      "blocklet.js",
      "README.md",
    ],
    gitHash: "b3d6a9f4af11922205074d1441965553eaa6a045",
    group: "static",
    homepage: "",
    interfaces: [
      {
        name: "publicUrl",
        path: "/",
        port: "BLOCKLET_PORT",
        prefix: "*",
        protocol: "tcp",
        type: "web",
      },
    ],
    keywords: ["Uniswap", "Ethereum"],
    license: "GPL-3.0-or-later",
    logo: "logo.png",
    main: "build",
    name: "uniswap-blocklet",
    nftFactory: "",
    path: "/static/uniswap-blocklet",
    payment: { price: [], share: [] },
    requirements: { abtnode: ">=1.1.0", cpu: "*", os: "*" },
    screenshots: [],
    scripts: {},
    signatures: [
      {
        type: "ED25519",
        name: "Blocklet Store",
        signer: "zNKXtdqz6Jbw5mKpojK2nP5gRNiEGJY3mNFF",
        pk: "z8VahoQa6oS63Ym3rfsmzZEt9Moonbg4JSUiit5J7DRAV",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-01-01T09:31:51.464Z",
        sig: "z2p2bpdzpbt11fMrGTZ3FxStrmBfzCA36soc9Jaw3dR8nnDCbJMoJbakBKtQ7YEtJ2J7bppnTRxxoy9VduhzGEDpU",
      },
      {
        appended: ["htmlAst", "lastPublishedAt", "stats"],
        created: "2022-01-01T09:31:29.857Z",
        excludes: ["htmlAst", "lastPublishedAt", "stats"],
        name: "uniswap-blocklet",
        pk: "z2eCsEyycLQPvqCRxvGBawGwyTfoZF1UpzocGqvtjdx7J",
        signer: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
        type: "ED25519",
        sig: "zn9y3mRP5KRTJbkVm9cEh8fRt8GdMHmxwkZsbAWUegP8UwsAfYDx6Qkw3PmK6rsdLxjsJ9MvPgeNz2EAWi5xCagc",
      },
      {
        created: "2021-12-29T03:00:25.851Z",
        name: "uniswap-blocklet",
        pk: "z75CxPgkoiANhn1iCMRHQX2w6fSQPgi2qZiqbhQuy9Xo3",
        sig: "z3VxpJx4t12qfVCtexKZptBjHaXSpJiDUzrkjcatjuoKYWVsq86RRAqpPkAiEMsPXRUg3mA7NwpydimPMUrm3t3G8",
        signer: "z1Rq9qSoqvAq1NcJJTzKB1AnM991Cm4JrzW",
        type: "ED25519",
      },
    ],
    specVersion: "1.2.0",
    timeout: { start: 10 },
    title: "Uniswap Blocklet",
    version: "0.2.7",
    stats: { downloads: 1533 },
    category: {
      name: "defi",
      locales: { zh: "去中心化金融", en: "DEFI" },
      _id: "GUjTm9sh6kXqgWWV",
      createdAt: "2022-01-11T01:52:32.325Z",
      updatedAt: "2022-01-11T01:52:32.325Z",
    },
    owner: {
      did: "z1euigAXVHi9cJfJGo2b9QaeQwxjQynSKoJ",
      name: "arcblock",
      role: "admin",
    },
    lastPublishedAt: "2021-12-29T03:00:28.591Z",
  },
];
